VOCABULARY = [
    # --- Day 1 ---
    {"kanji": '以外', "reading": 'いがい', "meaning": '除～之外、其他', "example_jp": '彼女以外の人は全員賛成した。', "example_zh": '除了她以外，所有人都同意了。', "day_group": 1},
    {"kanji": '影響', "reading": 'えいきょう', "meaning": '影響', "example_jp": '天気は気分に影響する。', "example_zh": '天氣會影響心情。', "day_group": 1},
    {"kanji": '意外', "reading": 'いがい', "meaning": '意外的、出乎意料', "example_jp": '彼の意外な才能に驚いた。', "example_zh": '對他意外的才能感到驚訝。', "day_group": 1},
    {"kanji": '改善', "reading": 'かいぜん', "meaning": '改善、改進', "example_jp": '生活習慣を改善することが大切だ。', "example_zh": '改善生活習慣很重要。', "day_group": 1},
    {"kanji": '確認', "reading": 'かくにん', "meaning": '確認、核對', "example_jp": '予約を確認してください。', "example_zh": '請確認預約。', "day_group": 1},
    {"kanji": '環境', "reading": 'かんきょう', "meaning": '環境', "example_jp": '環境問題は世界中で深刻だ。', "example_zh": '環境問題在全世界都很嚴重。', "day_group": 1},
    {"kanji": '技術', "reading": 'ぎじゅつ', "meaning": '技術、技能', "example_jp": '最新の技術を活用する。', "example_zh": '活用最新的技術。', "day_group": 1},
    {"kanji": '協力', "reading": 'きょうりょく', "meaning": '合作、協力', "example_jp": 'みんなで協力して問題を解決した。', "example_zh": '大家一起合作解決了問題。', "day_group": 1},
    {"kanji": '経験', "reading": 'けいけん', "meaning": '經驗、體驗', "example_jp": '海外での経験が役に立った。', "example_zh": '在國外的經驗很有幫助。', "day_group": 1},
    {"kanji": '結果', "reading": 'けっか', "meaning": '結果', "example_jp": '努力した結果、試験に合格した。', "example_zh": '努力的結果，通過了考試。', "day_group": 1},
    {"kanji": '現象', "reading": 'げんしょう', "meaning": '現象', "example_jp": 'この自然現象はまだ解明されていない。', "example_zh": '這個自然現象還沒有被解明。', "day_group": 1},
    {"kanji": '効果', "reading": 'こうか', "meaning": '效果、效用', "example_jp": 'この薬は効果があります。', "example_zh": '這個藥有效果。', "day_group": 1},
    {"kanji": '困難', "reading": 'こんなん', "meaning": '困難、艱難', "example_jp": '困難な状況でも諦めなかった。', "example_zh": '即使在困難的情況下也沒有放棄。', "day_group": 1},
    {"kanji": '最終', "reading": 'さいしゅう', "meaning": '最終、最後', "example_jp": '最終的な決定は社長が行う。', "example_zh": '最終的決定由社長做出。', "day_group": 1},
    {"kanji": '印象', "reading": 'いんしょう', "meaning": '印象', "example_jp": '彼女の笑顔が印象に残った。', "example_zh": '她的笑容給我留下了印象。', "day_group": 1},
    # --- Day 2 ---
    {"kanji": '参加', "reading": 'さんか', "meaning": '參加、加入', "example_jp": '会議に参加してください。', "example_zh": '請參加會議。', "day_group": 2},
    {"kanji": '支援', "reading": 'しえん', "meaning": '支援、支持', "example_jp": '被災地への支援が必要だ。', "example_zh": '需要對災區的支援。', "day_group": 2},
    {"kanji": '実現', "reading": 'じつげん', "meaning": '實現、達成', "example_jp": '夢を実現するために努力する。', "example_zh": '為了實現夢想而努力。', "day_group": 2},
    {"kanji": '状況', "reading": 'じょうきょう', "meaning": '狀況、情況', "example_jp": '現在の状況を説明してください。', "example_zh": '請說明目前的狀況。', "day_group": 2},
    {"kanji": '情報', "reading": 'じょうほう', "meaning": '資訊、信息', "example_jp": '最新の情報を集める。', "example_zh": '收集最新的資訊。', "day_group": 2},
    {"kanji": '承認', "reading": 'しょうにん', "meaning": '認可、批准', "example_jp": '計画が上司に承認された。', "example_zh": '計劃獲得了上司的批准。', "day_group": 2},
    {"kanji": '責任', "reading": 'せきにん', "meaning": '責任', "example_jp": '自分の行動に責任を持つ。', "example_zh": '對自己的行動負責。', "day_group": 2},
    {"kanji": '成功', "reading": 'せいこう', "meaning": '成功', "example_jp": 'プロジェクトが成功した。', "example_zh": '項目成功了。', "day_group": 2},
    {"kanji": '成長', "reading": 'せいちょう', "meaning": '成長、發展', "example_jp": '子どもの成長を見守る。', "example_zh": '守護孩子的成長。', "day_group": 2},
    {"kanji": '提案', "reading": 'ていあん', "meaning": '提案、建議', "example_jp": '新しい提案を考えた。', "example_zh": '想出了新的提案。', "day_group": 2},
    {"kanji": '努力', "reading": 'どりょく', "meaning": '努力', "example_jp": '毎日努力することが大切だ。', "example_zh": '每天努力是很重要的。', "day_group": 2},
    {"kanji": '把握', "reading": 'はあく', "meaning": '把握、掌握', "example_jp": '状況を把握する必要がある。', "example_zh": '需要掌握狀況。', "day_group": 2},
    {"kanji": '判断', "reading": 'はんだん', "meaning": '判斷', "example_jp": '正確な判断が求められる。', "example_zh": '需要正確的判斷。', "day_group": 2},
    {"kanji": '反省', "reading": 'はんせい', "meaning": '反省、反思', "example_jp": '自分の行動を反省した。', "example_zh": '對自己的行動進行了反省。', "day_group": 2},
    {"kanji": '批判', "reading": 'ひはん', "meaning": '批判、批評', "example_jp": '彼の行動は多くの批判を受けた。', "example_zh": '他的行動受到了很多批評。', "day_group": 2},
    # --- Day 3 ---
    {"kanji": '評価', "reading": 'ひょうか', "meaning": '評價、評估', "example_jp": '仕事の評価が上がった。', "example_zh": '工作的評價提高了。', "day_group": 3},
    {"kanji": '表現', "reading": 'ひょうげん', "meaning": '表現、表達', "example_jp": '自分の意見を上手に表現する。', "example_zh": '好好地表達自己的意見。', "day_group": 3},
    {"kanji": '普及', "reading": 'ふきゅう', "meaning": '普及、推廣', "example_jp": 'スマートフォンが世界中に普及した。', "example_zh": '智慧型手機普及到全世界。', "day_group": 3},
    {"kanji": '変化', "reading": 'へんか', "meaning": '變化', "example_jp": '社会は常に変化している。', "example_zh": '社會在不斷變化。', "day_group": 3},
    {"kanji": '方針', "reading": 'ほうしん', "meaning": '方針、政策', "example_jp": '会社の方針に従って仕事をする。', "example_zh": '按照公司的方針工作。', "day_group": 3},
    {"kanji": '豊か', "reading": 'ゆたか', "meaning": '豐富的、富裕的', "example_jp": '自然豊かな環境で育った。', "example_zh": '在自然豐富的環境中成長。', "day_group": 3},
    {"kanji": '予測', "reading": 'よそく', "meaning": '預測、預料', "example_jp": '天気を予測するのは難しい。', "example_zh": '預測天氣很難。', "day_group": 3},
    {"kanji": '理解', "reading": 'りかい', "meaning": '理解、了解', "example_jp": '相手の立場を理解する。', "example_zh": '理解對方的立場。', "day_group": 3},
    {"kanji": '利用', "reading": 'りよう', "meaning": '利用、使用', "example_jp": '公共交通を利用する。', "example_zh": '利用公共交通。', "day_group": 3},
    {"kanji": '論文', "reading": 'ろんぶん', "meaning": '論文', "example_jp": '卒業論文を提出した。', "example_zh": '提交了畢業論文。', "day_group": 3},
    {"kanji": '観察', "reading": 'かんさつ', "meaning": '觀察', "example_jp": '自然を観察するのが好きだ。', "example_zh": '喜歡觀察自然。', "day_group": 3},
    {"kanji": '規則', "reading": 'きそく', "meaning": '規則、規定', "example_jp": '規則を守ることが重要だ。', "example_zh": '遵守規則很重要。', "day_group": 3},
    {"kanji": '緊張', "reading": 'きんちょう', "meaning": '緊張', "example_jp": '発表前に緊張してしまった。', "example_zh": '在發表前緊張了。', "day_group": 3},
    {"kanji": '誠実', "reading": 'せいじつ', "meaning": '誠實、誠懇', "example_jp": '誠実な態度で仕事に取り組む。', "example_zh": '以誠實的態度投入工作。', "day_group": 3},
    {"kanji": '以降', "reading": 'いこう', "meaning": '～之後、此後', "example_jp": '来週以降、新しいシステムを使います。', "example_zh": '下週之後，將使用新系統。', "day_group": 3},
    # --- N2 Day 4 ---
    {"kanji": '余裕', "reading": 'よゆう', "meaning": '餘裕、從容', "example_jp": '時間に余裕があるうちに準備しておこう。', "example_zh": '趁時間還充裕的時候先準備好吧。', "day_group": 4},
    {"kanji": '対策', "reading": 'たいさく', "meaning": '對策、應對措施', "example_jp": '騒音対策として窓を二重にした。', "example_zh": '為了隔音對策，把窗戶換成了雙層。', "day_group": 4},
    {"kanji": '範囲', "reading": 'はんい', "meaning": '範圍', "example_jp": '試験の範囲を先生に確認した。', "example_zh": '向老師確認了考試的範圍。', "day_group": 4},
    {"kanji": '明確', "reading": 'めいかく', "meaning": '明確、清楚', "example_jp": '目的を明確にすることが重要だ。', "example_zh": '明確目的是很重要的。', "day_group": 4},
    {"kanji": '根拠', "reading": 'こんきょ', "meaning": '根據、依據', "example_jp": '根拠のない噂を信じてはいけない。', "example_zh": '不能相信沒有根據的謠言。', "day_group": 4},
    {"kanji": '促進', "reading": 'そくしん', "meaning": '促進', "example_jp": '運動は血液循環を促進する。', "example_zh": '運動能促進血液循環。', "day_group": 4},
    {"kanji": '維持', "reading": 'いじ', "meaning": '維持、保持', "example_jp": '健康を維持するために食事に気をつける。', "example_zh": '為了維持健康，注意飲食。', "day_group": 4},
    {"kanji": '概要', "reading": 'がいよう', "meaning": '概要、大綱', "example_jp": '会議の概要をまとめて報告した。', "example_zh": '整理了會議概要並進行報告。', "day_group": 4},
    {"kanji": '承知', "reading": 'しょうち', "meaning": '了解、知道', "example_jp": '事情は承知しております。', "example_zh": '我了解情況。', "day_group": 4},
    {"kanji": '妥当', "reading": 'だとう', "meaning": '妥當、適當', "example_jp": '彼の判断は妥当だと思う。', "example_zh": '我認為他的判斷很妥當。', "day_group": 4},
    {"kanji": '補足', "reading": 'ほそく', "meaning": '補充、補足', "example_jp": '説明が不十分だったので補足した。', "example_zh": '說明不夠充分，所以補充說明了。', "day_group": 4},
    {"kanji": '要因', "reading": 'よういん', "meaning": '原因、要因', "example_jp": '失敗の要因を徹底的に分析した。', "example_zh": '徹底分析了失敗的原因。', "day_group": 4},
    {"kanji": '連携', "reading": 'れんけい', "meaning": '合作、聯動', "example_jp": '部門間で連携して問題を解決した。', "example_zh": '各部門合作解決了問題。', "day_group": 4},
    {"kanji": '敬意', "reading": 'けいい', "meaning": '敬意', "example_jp": '先輩に対して敬意を持って接する。', "example_zh": '以敬意對待前輩。', "day_group": 4},
    {"kanji": '妨害', "reading": 'ぼうがい', "meaning": '妨礙、阻礙', "example_jp": '工事の騒音が勉強の妨害になっている。', "example_zh": '工程噪音妨礙了學習。', "day_group": 4},
    {"kanji": '背景', "reading": 'はいけい', "meaning": '背景', "example_jp": '事件の背景を詳しく調べた。', "example_zh": '詳細調查了事件的背景。', "day_group": 4},
    {"kanji": '役割', "reading": 'やくわり', "meaning": '角色、職責', "example_jp": 'チームの中での自分の役割を理解する。', "example_zh": '理解自己在團隊中的角色。', "day_group": 4},
    {"kanji": '配慮', "reading": 'はいりょ', "meaning": '體貼、考量', "example_jp": '相手の気持ちへの配慮が大切だ。', "example_zh": '對對方感受的體貼很重要。', "day_group": 4},
    {"kanji": '論理', "reading": 'ろんり', "meaning": '邏輯', "example_jp": '論理的に考えることが科学の基本だ。', "example_zh": '邏輯性地思考是科學的基本。', "day_group": 4},
    {"kanji": '目標', "reading": 'もくひょう', "meaning": '目標', "example_jp": '具体的な目標を立てると達成しやすい。', "example_zh": '訂立具體目標的話比較容易達成。', "day_group": 4},
    # --- N2 Day 5 ---
    {"kanji": '継続', "reading": 'けいぞく', "meaning": '繼續、持續', "example_jp": '練習を継続することが上達の近道だ。', "example_zh": '持續練習是進步的捷徑。', "day_group": 5},
    {"kanji": '限界', "reading": 'げんかい', "meaning": '極限、限界', "example_jp": '自分の限界に挑戦し続けた。', "example_zh": '持續挑戰自己的極限。', "day_group": 5},
    {"kanji": '構造', "reading": 'こうぞう', "meaning": '構造', "example_jp": '建物の構造を専門家に調べてもらった。', "example_zh": '請專家調查了建築物的構造。', "day_group": 5},
    {"kanji": '採用', "reading": 'さいよう', "meaning": '採用、錄用', "example_jp": '会社に採用されて嬉しかった。', "example_zh": '被公司錄用了，很開心。', "day_group": 5},
    {"kanji": '充実', "reading": 'じゅうじつ', "meaning": '充實', "example_jp": '毎日が充実していると感じる。', "example_zh": '感覺每天都很充實。', "day_group": 5},
    {"kanji": '設立', "reading": 'せつりつ', "meaning": '設立、成立', "example_jp": '新しい会社を設立する計画を立てた。', "example_zh": '制定了設立新公司的計劃。', "day_group": 5},
    {"kanji": '相互', "reading": 'そうご', "meaning": '相互、彼此', "example_jp": '相互理解が良い関係の基本だ。', "example_zh": '相互理解是良好關係的基礎。', "day_group": 5},
    {"kanji": '依存', "reading": 'いぞん', "meaning": '依賴、依存', "example_jp": 'スマホへの依存が問題になっている。', "example_zh": '對智慧型手機的依賴成了問題。', "day_group": 5},
    {"kanji": '応用', "reading": 'おうよう', "meaning": '應用', "example_jp": '学んだ知識を実際の問題に応用する。', "example_zh": '將學到的知識應用於實際問題。', "day_group": 5},
    {"kanji": '過程', "reading": 'かてい', "meaning": '過程', "example_jp": '結果だけでなく過程も大切にしたい。', "example_zh": '不只是結果，也想重視過程。', "day_group": 5},
    {"kanji": '議論', "reading": 'ぎろん', "meaning": '討論、議論', "example_jp": '活発な議論が行われた。', "example_zh": '進行了熱烈的討論。', "day_group": 5},
    {"kanji": '感謝', "reading": 'かんしゃ', "meaning": '感謝', "example_jp": '周りの人への感謝を忘れないようにする。', "example_zh": '不忘對周圍人的感謝。', "day_group": 5},
    {"kanji": '均等', "reading": 'きんとう', "meaning": '均等、平均', "example_jp": '作業を均等に分担した。', "example_zh": '均等分配了工作。', "day_group": 5},
    {"kanji": '整備', "reading": 'せいび', "meaning": '整備、整頓', "example_jp": '機械を定期的に整備する必要がある。', "example_zh": '需要定期整備機械。', "day_group": 5},
    {"kanji": '一般', "reading": 'いっぱん', "meaning": '一般、普通', "example_jp": '一般的な方法で問題を解いた。', "example_zh": '用一般的方法解決了問題。', "day_group": 5},
    {"kanji": '分析', "reading": 'ぶんせき', "meaning": '分析', "example_jp": 'データを詳しく分析した結果、傾向が見えてきた。', "example_zh": '詳細分析資料後，看出了趨勢。', "day_group": 5},
    {"kanji": '比較', "reading": 'ひかく', "meaning": '比較', "example_jp": '二つの商品を比較して安い方を選んだ。', "example_zh": '比較了兩個商品，選了較便宜的。', "day_group": 5},
    {"kanji": '要求', "reading": 'ようきゅう', "meaning": '要求', "example_jp": '顧客の要求に応えるために努力した。', "example_zh": '為了回應客戶的要求而努力。', "day_group": 5},
    {"kanji": '認識', "reading": 'にんしき', "meaning": '認識、認知', "example_jp": '問題の深刻さを改めて認識した。', "example_zh": '重新認識到問題的嚴重性。', "day_group": 5},
    {"kanji": '発揮', "reading": 'はっき', "meaning": '發揮', "example_jp": '本番で実力を発揮することができた。', "example_zh": '在正式場合發揮了實力。', "day_group": 5},
    # --- N2 Day 6 ---
    {"kanji": '短縮', "reading": 'たんしゅく', "meaning": '縮短', "example_jp": '作業時間を大幅に短縮することができた。', "example_zh": '大幅縮短了作業時間。', "day_group": 6},
    {"kanji": '徹底', "reading": 'てってい', "meaning": '徹底', "example_jp": '衛生管理を徹底することが求められる。', "example_zh": '要求徹底做好衛生管理。', "day_group": 6},
    {"kanji": '展開', "reading": 'てんかい', "meaning": '展開、發展', "example_jp": '新しいビジネスを海外に展開する。', "example_zh": '將新事業展開到海外。', "day_group": 6},
    {"kanji": '同様', "reading": 'どうよう', "meaning": '同樣、相同', "example_jp": '昨年と同様の結果が出た。', "example_zh": '出現了與去年相同的結果。', "day_group": 6},
    {"kanji": '保存', "reading": 'ほぞん', "meaning": '保存', "example_jp": '食品を適切な温度で保存する。', "example_zh": '以適當的溫度保存食品。', "day_group": 6},
    {"kanji": '利益', "reading": 'りえき', "meaning": '利益、好處', "example_jp": '会社の利益よりも社会への貢献を優先した。', "example_zh": '優先考量對社會的貢獻，而非公司利益。', "day_group": 6},
    {"kanji": '優先', "reading": 'ゆうせん', "meaning": '優先', "example_jp": '安全を最優先に考えてください。', "example_zh": '請以安全為最優先考量。', "day_group": 6},
    {"kanji": '向上', "reading": 'こうじょう', "meaning": '提升、進步', "example_jp": 'スキルの向上のために毎日練習する。', "example_zh": '每天練習以提升技能。', "day_group": 6},
    {"kanji": '交流', "reading": 'こうりゅう', "meaning": '交流', "example_jp": '異文化交流を通じて視野が広がった。', "example_zh": '透過跨文化交流開拓了視野。', "day_group": 6},
    {"kanji": '公正', "reading": 'こうせい', "meaning": '公正、公平', "example_jp": '公正な判断をすることが裁判官の使命だ。', "example_zh": '做出公正的判斷是法官的使命。', "day_group": 6},
    {"kanji": '最適', "reading": 'さいてき', "meaning": '最適合、最佳', "example_jp": '最適な解決策を探し続けた。', "example_zh": '持續尋找最佳解決方案。', "day_group": 6},
    {"kanji": '自立', "reading": 'じりつ', "meaning": '自立、獨立', "example_jp": '親に頼らず自立して生きていきたい。', "example_zh": '想不依靠父母、自立生活。', "day_group": 6},
    {"kanji": '集中', "reading": 'しゅうちゅう', "meaning": '集中', "example_jp": '試験前は勉強に集中した。', "example_zh": '考試前集中念書。', "day_group": 6},
    {"kanji": '原因', "reading": 'げんいん', "meaning": '原因', "example_jp": '事故の原因を調査している。', "example_zh": '正在調查事故的原因。', "day_group": 6},
    {"kanji": '解決', "reading": 'かいけつ', "meaning": '解決', "example_jp": '問題を早急に解決する必要がある。', "example_zh": '需要盡快解決問題。', "day_group": 6},
    {"kanji": '活動', "reading": 'かつどう', "meaning": '活動', "example_jp": 'ボランティア活動に積極的に参加している。', "example_zh": '積極參與志工活動。', "day_group": 6},
    {"kanji": '行動', "reading": 'こうどう', "meaning": '行動', "example_jp": '考えるだけでなく、実際に行動することが大切だ。', "example_zh": '不只是思考，實際行動也很重要。', "day_group": 6},
    {"kanji": '安定', "reading": 'あんてい', "meaning": '安定、穩定', "example_jp": '安定した収入を得ることが目標だ。', "example_zh": '獲得穩定收入是目標。', "day_group": 6},
    {"kanji": '適切', "reading": 'てきせつ', "meaning": '適切、恰當', "example_jp": '適切な言葉を選んで伝えることが重要だ。', "example_zh": '選擇恰當的言詞傳達是很重要的。', "day_group": 6},
    {"kanji": '目的', "reading": 'もくてき', "meaning": '目的', "example_jp": '旅行の目的は文化を学ぶことだ。', "example_zh": '旅行的目的是學習文化。', "day_group": 6},
    # --- N1 Day 7 ---
    {"kanji": '曖昧', "reading": 'あいまい', "meaning": '模糊、曖昧', "example_jp": '曖昧な返答では相手を混乱させてしまう。', "example_zh": '模糊的回答會讓對方困惑。', "day_group": 7},
    {"kanji": '一貫', "reading": 'いっかん', "meaning": '一貫、始終如一', "example_jp": '彼は一貫した姿勢で仕事に取り組んでいる。', "example_zh": '他以一貫的態度投入工作。', "day_group": 7},
    {"kanji": '醸成', "reading": 'じょうせい', "meaning": '醞釀、培養', "example_jp": '信頼関係を醸成するには時間がかかる。', "example_zh": '培養信任關係需要時間。', "day_group": 7},
    {"kanji": '前提', "reading": 'ぜんてい', "meaning": '前提', "example_jp": '互いに協力するという前提で計画を立てた。', "example_zh": '以彼此合作為前提制定了計劃。', "day_group": 7},
    {"kanji": '統合', "reading": 'とうごう', "meaning": '整合、統合', "example_jp": '二つのシステムを統合する作業が始まった。', "example_zh": '開始了整合兩個系統的作業。', "day_group": 7},
    {"kanji": '概念', "reading": 'がいねん', "meaning": '概念', "example_jp": '新しい概念を理解するには時間がかかる。', "example_zh": '理解新概念需要時間。', "day_group": 7},
    {"kanji": '潜在', "reading": 'せんざい', "meaning": '潛在', "example_jp": '潜在的なリスクを事前に把握しておく。', "example_zh": '事先掌握潛在的風險。', "day_group": 7},
    {"kanji": '矛盾', "reading": 'むじゅん', "meaning": '矛盾', "example_jp": '彼の言動には矛盾がある。', "example_zh": '他的言行有矛盾。', "day_group": 7},
    {"kanji": '包括', "reading": 'ほうかつ', "meaning": '包括、涵蓋', "example_jp": '包括的なアプローチで問題に取り組む。', "example_zh": '以全面的方式處理問題。', "day_group": 7},
    {"kanji": '懸念', "reading": 'けねん', "meaning": '擔憂、顧慮', "example_jp": '安全面への懸念から計画を見直した。', "example_zh": '基於對安全方面的擔憂，重新審視了計劃。', "day_group": 7},
    {"kanji": '抽象', "reading": 'ちゅうしょう', "meaning": '抽象', "example_jp": '抽象的な説明では理解しにくい。', "example_zh": '抽象的說明很難理解。', "day_group": 7},
    {"kanji": '模索', "reading": 'もさく', "meaning": '摸索、探索', "example_jp": '解決策を模索している段階だ。', "example_zh": '目前還在摸索解決方案的階段。', "day_group": 7},
    {"kanji": '逸脱', "reading": 'いつだつ', "meaning": '脫離、越軌', "example_jp": '規範から逸脱した行動は許されない。', "example_zh": '脫離規範的行為是不被允許的。', "day_group": 7},
    {"kanji": '斬新', "reading": 'ざんしん', "meaning": '嶄新、創新', "example_jp": '斬新なデザインが話題を呼んだ。', "example_zh": '嶄新的設計引起了話題。', "day_group": 7},
    {"kanji": '創出', "reading": 'そうしゅつ', "meaning": '創造、創出', "example_jp": '新たな価値を創出することが求められる。', "example_zh": '被要求創造新的價值。', "day_group": 7},
    {"kanji": '適宜', "reading": 'てきぎ', "meaning": '適當地、適時', "example_jp": '状況に応じて適宜対応してください。', "example_zh": '請根據情況適當應對。', "day_group": 7},
    {"kanji": '是正', "reading": 'ぜせい', "meaning": '糾正、矯正', "example_jp": '不公正な慣行を是正する必要がある。', "example_zh": '需要糾正不公正的慣例。', "day_group": 7},
    {"kanji": '打開', "reading": 'だかい', "meaning": '突破、打開局面', "example_jp": '困難な状況を打開する方法を考えた。', "example_zh": '思考了突破困難局面的方法。', "day_group": 7},
    {"kanji": '顕著', "reading": 'けんちょ', "meaning": '顯著、明顯', "example_jp": '気温上昇の影響が顕著に現れている。', "example_zh": '氣溫上升的影響明顯地顯現出來。', "day_group": 7},
    {"kanji": '均衡', "reading": 'きんこう', "meaning": '均衡、平衡', "example_jp": '需要と供給の均衡を保つことが大切だ。', "example_zh": '保持需求與供給的均衡很重要。', "day_group": 7},
    # --- N1 Day 8 ---
    {"kanji": '脆弱', "reading": 'ぜいじゃく', "meaning": '脆弱', "example_jp": 'セキュリティの脆弱性が発見された。', "example_zh": '發現了安全性的脆弱漏洞。', "day_group": 8},
    {"kanji": '抑制', "reading": 'よくせい', "meaning": '抑制、壓制', "example_jp": '感情を抑制することが求められる場面もある。', "example_zh": '也有需要抑制情感的場合。', "day_group": 8},
    {"kanji": '廃止', "reading": 'はいし', "meaning": '廢止、廢除', "example_jp": '古い制度を廃止して新しいルールを導入した。', "example_zh": '廢除了舊制度，引進了新規則。', "day_group": 8},
    {"kanji": '固執', "reading": 'こしつ', "meaning": '固執、堅持', "example_jp": '自分の意見に固執しすぎるのは問題だ。', "example_zh": '過於固執己見是個問題。', "day_group": 8},
    {"kanji": '妥協', "reading": 'だきょう', "meaning": '妥協', "example_jp": '品質に妥協することは絶対にしない。', "example_zh": '絕對不在品質上妥協。', "day_group": 8},
    {"kanji": '払拭', "reading": 'ふっしょく', "meaning": '消除、掃除', "example_jp": '不安を払拭するために詳しく説明した。', "example_zh": '為了消除不安，詳細說明了。', "day_group": 8},
    {"kanji": '虚偽', "reading": 'きょぎ', "meaning": '虛偽、謊言', "example_jp": '虚偽の情報を流してはならない。', "example_zh": '不可散布虛假資訊。', "day_group": 8},
    {"kanji": '著しい', "reading": 'いちじるしい', "meaning": '顯著的、明顯的', "example_jp": '技術の進歩は著しい。', "example_zh": '技術的進步十分顯著。', "day_group": 8},
    {"kanji": '乖離', "reading": 'かいり', "meaning": '背離、乖離', "example_jp": '理想と現実の乖離を感じることがある。', "example_zh": '有時會感受到理想與現實的背離。', "day_group": 8},
    {"kanji": '折衝', "reading": 'せっしょう', "meaning": '折衝、交涉', "example_jp": '両者の間で折衝が続いている。', "example_zh": '兩方之間的交涉持續進行中。', "day_group": 8},
    {"kanji": '刷新', "reading": 'さっしん', "meaning": '革新、刷新', "example_jp": 'チームの雰囲気を刷新するために新しい方針を導入した。', "example_zh": '為了刷新團隊氣氛，導入了新方針。', "day_group": 8},
    {"kanji": '帰結', "reading": 'きけつ', "meaning": '結論、歸結', "example_jp": '長い議論の帰結として、提案が採択された。', "example_zh": '作為長時間討論的結論，提案被採納了。', "day_group": 8},
    {"kanji": '策定', "reading": 'さくてい', "meaning": '制定、擬定', "example_jp": '新たな方針を策定するための委員会が設置された。', "example_zh": '設立了為制定新方針的委員會。', "day_group": 8},
    {"kanji": '担う', "reading": 'になう', "meaning": '承擔、負擔', "example_jp": '次世代を担う人材を育てることが重要だ。', "example_zh": '培育承擔下一代的人才很重要。', "day_group": 8},
    {"kanji": '見込み', "reading": 'みこみ', "meaning": '預期、展望', "example_jp": '来月には完成する見込みだ。', "example_zh": '預計下個月完成。', "day_group": 8},
    {"kanji": '逆説', "reading": 'ぎゃくせつ', "meaning": '矛盾、悖論', "example_jp": '逆説的だが、失敗が成功への近道になることがある。', "example_zh": '雖然矛盾，但失敗有時成為成功的捷徑。', "day_group": 8},
    {"kanji": '相乗', "reading": 'そうじょう', "meaning": '相乘、加乘效果', "example_jp": '二つの技術を組み合わせることで相乗効果が生まれる。', "example_zh": '結合兩種技術能產生相乘效果。', "day_group": 8},
    {"kanji": '帰納', "reading": 'きのう', "meaning": '歸納', "example_jp": '帰納的な推論で結論を導き出した。', "example_zh": '用歸納推理導出了結論。', "day_group": 8},
    {"kanji": '演繹', "reading": 'えんえき', "meaning": '演繹', "example_jp": '演繹的な方法で問題にアプローチした。', "example_zh": '以演繹的方式解決了問題。', "day_group": 8},
    {"kanji": '即座', "reading": 'そくざ', "meaning": '立即、馬上', "example_jp": '問題が発生した際、即座に対応することが大切だ。', "example_zh": '發生問題時，立即應對很重要。', "day_group": 8},
    # --- N1 Day 9 ---
    {"kanji": '内包', "reading": 'ないほう', "meaning": '包含、內含', "example_jp": 'この政策は多くのリスクを内包している。', "example_zh": '這項政策包含許多風險。', "day_group": 9},
    {"kanji": '抜粋', "reading": 'ばっすい', "meaning": '摘錄、節選', "example_jp": '報告書から重要な部分を抜粋して紹介した。', "example_zh": '從報告書中摘錄重要部分介紹。', "day_group": 9},
    {"kanji": '促す', "reading": 'うながす', "meaning": '催促、促進', "example_jp": '医師は患者に早期の治療を促した。', "example_zh": '醫師催促患者接受早期治療。', "day_group": 9},
    {"kanji": '賄う', "reading": 'まかなう', "meaning": '供應、籌措', "example_jp": '全費用を奨学金で賄うのは難しい。', "example_zh": '用獎學金籌措全部費用很困難。', "day_group": 9},
    {"kanji": '収斂', "reading": 'しゅうれん', "meaning": '收斂、趨同', "example_jp": '議論はようやく一つの結論に収斂した。', "example_zh": '討論終於收斂到一個結論。', "day_group": 9},
    {"kanji": '凌駕', "reading": 'りょうが', "meaning": '凌駕、超越', "example_jp": '彼の技術は他の選手を凌駕している。', "example_zh": '他的技術凌駕其他選手。', "day_group": 9},
    {"kanji": '示唆', "reading": 'しさ', "meaning": '暗示、啟示', "example_jp": 'このデータは問題の深刻さを示唆している。', "example_zh": '這份資料暗示了問題的嚴重性。', "day_group": 9},
    {"kanji": '喚起', "reading": 'かんき', "meaning": '喚起、喚醒', "example_jp": '危険性への注意を喚起するキャンペーンを実施した。', "example_zh": '實施了喚起對危險性注意的宣傳活動。', "day_group": 9},
    {"kanji": '脅威', "reading": 'きょうい', "meaning": '威脅', "example_jp": 'サイバー攻撃は現代社会への大きな脅威だ。', "example_zh": '網路攻擊是對現代社會的重大威脅。', "day_group": 9},
    {"kanji": '惹起', "reading": 'じゃっき', "meaning": '引發、招致', "example_jp": '不適切な発言が問題を惹起した。', "example_zh": '不當的發言引發了問題。', "day_group": 9},
    {"kanji": '拮抗', "reading": 'きっこう', "meaning": '拮抗、相抗衡', "example_jp": '両チームは最後まで拮抗した試合を見せた。', "example_zh": '兩隊直到最後都打了一場相互抗衡的比賽。', "day_group": 9},
    {"kanji": '俯瞰', "reading": 'ふかん', "meaning": '俯瞰、全局視角', "example_jp": '問題を俯瞰的に見ることが解決の糸口になる。', "example_zh": '從全局角度看問題，成為解決的線索。', "day_group": 9},
    {"kanji": '没入', "reading": 'ぼつにゅう', "meaning": '沉浸、投入', "example_jp": '研究に没入するあまり、食事も忘れてしまった。', "example_zh": '太沉浸於研究，連吃飯都忘了。', "day_group": 9},
    {"kanji": '邁進', "reading": 'まいしん', "meaning": '邁進、奮力前進', "example_jp": '目標に向かって邁進する姿が感動を呼んだ', "example_zh": '向目標邁進的姿態令人感動。', "day_group": 9},
    {"kanji": '危惧', "reading": 'きぐ', "meaning": '擔憂、憂慮', "example_jp": '環境破壊への危惧が高まっている。', "example_zh": '對環境破壞的擔憂日益加深。', "day_group": 9},
    {"kanji": '齟齬', "reading": 'そご', "meaning": '齟齬、不協調', "example_jp": '認識の齟齬が誤解を生んだ。', "example_zh": '認知上的齟齬產生了誤解。', "day_group": 9},
    {"kanji": '看過', "reading": 'かんか', "meaning": '忽視、視而不見', "example_jp": 'このような問題は看過できない。', "example_zh": '這樣的問題不能視而不見。', "day_group": 9},
    {"kanji": '加味', "reading": 'かみ', "meaning": '加入考量、加進', "example_jp": 'リスクも加味した上で判断してください。', "example_zh": '請在將風險也加入考量後再做判斷。', "day_group": 9},
    {"kanji": '賛否', "reading": 'さんぴ', "meaning": '贊否、支持與反對', "example_jp": '新しい政策に対して賛否が分かれている。', "example_zh": '對新政策的支持與反對意見分歧。', "day_group": 9},
    {"kanji": '肝要', "reading": 'かんよう', "meaning": '要緊、重要', "example_jp": '信頼を築くことが交渉において肝要だ。', "example_zh": '建立信任在交涉中是最重要的。', "day_group": 9},
]


QUESTIONS = [
    {
        "type": 'kanji',
        "context": None,
        "question": '「彼は困難な課題に挑戦した。」下線部「困難」の読み方として正しいものはどれですか。',
        "option_a": 'こんなん',
        "option_b": 'こんにち',
        "option_c": 'こんなく',
        "option_d": 'こんだん',
        "correct_answer": 'a',
        "explanation": '困難（こんなん）＝ 困難、艱難。「困」は「こん」、「難」は「なん」と読みます。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「環境問題への意識が高まっている。」下線部「意識」の読み方として正しいものはどれですか。',
        "option_a": 'いみ',
        "option_b": 'いしき',
        "option_c": 'いそく',
        "option_d": 'いじき',
        "correct_answer": 'b',
        "explanation": '意識（いしき）＝ 意識、認識。「意」は「い」、「識」は「しき」と読みます。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「彼女の誠実な態度に感動した。」下線部「誠実」の読み方として正しいものはどれですか。',
        "option_a": 'せいじつ',
        "option_b": 'まじめ',
        "option_c": 'せいしつ',
        "option_d": 'しょうじつ',
        "correct_answer": 'a',
        "explanation": '誠実（せいじつ）＝ 誠實。「誠」は「せい」、「実」は「じつ」と読みます。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「その現象はまだ解明されていない。」下線部「現象」の読み方として正しいものはどれですか。',
        "option_a": 'げんぞう',
        "option_b": 'けんしょう',
        "option_c": 'げんしょう',
        "option_d": 'げんじょう',
        "correct_answer": 'c',
        "explanation": '現象（げんしょう）＝ 現象。「現」は「げん」、「象」は「しょう」と読みます。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「会社の方針を承認した。」下線部「承認」の読み方として正しいものはどれですか。',
        "option_a": 'しょうにん',
        "option_b": 'しょうめい',
        "option_c": 'そうにん',
        "option_d": 'しょうごん',
        "correct_answer": 'a',
        "explanation": '承認（しょうにん）＝ 認可、批准。「承」は「しょう」、「認」は「にん」と読みます。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「雨が降っていた（\u3000\u3000）、彼は傘をささずに外に出た。」（\u3000\u3000）に入る言葉として最も適切なものはどれですか。',
        "option_a": 'にもかかわらず',
        "option_b": 'ので',
        "option_c": 'から',
        "option_d": 'ために',
        "correct_answer": 'a',
        "explanation": '「にもかかわらず」は逆接を表し「～であるのに、それに反して」という意味。中文：雖然下雨，但他沒有撐傘就出去了。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「この薬の効果は人（\u3000\u3000）異なる。」（\u3000\u3000）に入る言葉として最も適切なものはどれですか。',
        "option_a": 'について',
        "option_b": 'に対して',
        "option_c": 'によって',
        "option_d": 'に関して',
        "correct_answer": 'c',
        "explanation": '「によって」は差異・原因・手段を表します。「人によって異なる」＝ 因人而異。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「社長を（\u3000\u3000）、社員全員がパーティーに参加した。」（\u3000\u3000）に入る言葉として最も適切なものはどれですか。',
        "option_a": 'はじめ',
        "option_b": 'もとに',
        "option_c": 'ともに',
        "option_d": 'かわりに',
        "correct_answer": 'a',
        "explanation": '「をはじめ（として）」は「～を代表的な例として、その他も含む」という意味。中文：以社長為首，全體員工都參加了派對。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「彼女の発言に（\u3000\u3000）、様々な意見が出た。」（\u3000\u3000）に入る言葉として最も適切なものはどれですか。',
        "option_a": 'よって',
        "option_b": '対して',
        "option_c": 'ついて',
        "option_d": '関して',
        "correct_answer": 'b',
        "explanation": '「に対して」は「～を対象として反応・行動する」という意味。中文：對於她的發言，提出了各種意見。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「十分な準備を（\u3000\u3000）、本番に臨むことが大切だ。」（\u3000\u3000）に入る言葉として最も適切なものはどれですか。',
        "option_a": 'するために',
        "option_b": 'しながら',
        "option_c": 'した上で',
        "option_d": 'したとたん',
        "correct_answer": 'c',
        "explanation": '「た上で」は「～してから、その後で（次のステップへ）」という意味。中文：做好充分準備之後，上場是很重要的。',
    },
    {
        "type": 'listening',
        "context": '【場面の説明】\n会社の会議室で、田中さんと佐藤さんが話しています。\n\n田中：「来週の企画発表、準備はどう？」\n佐藤：「もう少しで終わります。でも、データの分析がまだ完成していないんです。」\n田中：「それは大変だね。手伝えることはある？」\n佐藤：「ありがとうございます。グラフを作るのを手伝っていただければ助かります。」\n田中：「分かった。じゃあ明日一緒にやろう。」',
        "question": '佐藤さんが田中さんにお願いしたいことは何ですか？',
        "option_a": 'グラフを作ること',
        "option_b": 'データを分析すること',
        "option_c": '企画書を書くこと',
        "option_d": '発表の練習をすること',
        "correct_answer": 'a',
        "explanation": '佐藤さんは「グラフを作るのを手伝っていただければ助かります」と言っているので、正解は「グラフを作ること」です。',
    },
    {
        "type": 'listening',
        "context": '【場面の説明】\n鈴木さんが病院に電話しています。\n\n受付：「はい、田中クリニックです。」\n鈴木：「予約を取りたいのですが、今週の木曜日は空いていますか？」\n受付：「木曜日は午前中だけですが、10時はいかがでしょうか？」\n鈴木：「10時は少し早いんですが、11時はどうですか？」\n受付：「11時は予約で一杯です。10時半はいかがですか？」\n鈴木：「じゃあ、10時半でお願いします。」',
        "question": '鈴木さんはいつ予約を取りましたか？',
        "option_a": '木曜日の10時',
        "option_b": '木曜日の10時半',
        "option_c": '木曜日の11時',
        "option_d": '木曜日の午後',
        "correct_answer": 'b',
        "explanation": '最終的に「10時半でお願いします」と言っているので、正解は「木曜日の10時半」です。',
    },
    {
        "type": 'listening',
        "context": '【場面の説明】\nラジオでニュースが流れています。\n\nアナウンサー：「本日、市内の図書館が新しいサービスを開始しました。このサービスでは、スマートフォンのアプリを使って本を借りることができます。利用者はアプリをダウンロードして、読みたい本を選ぶだけで、最大3冊まで2週間借りることができます。返却はアプリ上で手続きをするだけで完了します。なお、アプリは無料でダウンロードできます。」',
        "question": '新しいサービスについて正しいものはどれですか？',
        "option_a": '最大5冊まで借りることができる',
        "option_b": '返却期限は1週間だ',
        "option_c": '最大3冊まで2週間借りられる',
        "option_d": 'アプリのダウンロードは有料だ',
        "correct_answer": 'c',
        "explanation": '「最大3冊まで2週間借りることができます」と言っています。a（5冊）・b（1週間）・d（有料）はいずれも誤りです。',
    },
    {
        "type": 'listening',
        "context": '【場面の説明】\n大学の説明会で、職員が話しています。\n\n職員：「本学の交換留学プログラムについてご説明します。このプログラムでは、協定を結んでいる海外の大学に1年間留学することができます。応募資格は、2年生以上で、GPA3.0以上の学生です。また、留学先の言語能力証明書が必要です。応募締め切りは毎年10月末となっております。詳細は学生課にお問い合わせください。」',
        "question": '交換留学プログラムに応募できる学生はどれですか？',
        "option_a": '1年生でGPAが3.0以上の学生',
        "option_b": '2年生でGPAが3.0以上の学生',
        "option_c": '3年生以上の学生のみ',
        "option_d": '語学証明書がなくても応募できる学生',
        "correct_answer": 'b',
        "explanation": '「2年生以上で、GPA3.0以上」が応募資格です。1年生は応募不可で、語学証明書も必須です。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n現代社会において、スマートフォンは私たちの日常生活に欠かせない存在となっている。買い物、コミュニケーション、情報収集など、様々な場面で活用されている。しかし、その便利さの一方で、スマートフォンへの依存度が高まり、人間関係や集中力に悪影響を与えるという問題も指摘されている。特に若い世代では、就寝前にスマートフォンを使う習慣が睡眠の質を低下させているという研究結果もある。このような問題に対処するためには、スマートフォンの使用時間を自分でコントロールする意識を持つことが重要だ。',
        "question": '文章の内容として正しいものはどれですか？',
        "option_a": 'スマートフォンの使用は人間関係を改善する',
        "option_b": 'スマートフォンは買い物にしか使えない',
        "option_c": '就寝前のスマートフォン使用が若者の睡眠の質を低下させている',
        "option_d": 'スマートフォンは現代社会では必要ない',
        "correct_answer": 'c',
        "explanation": '「就寝前にスマートフォンを使う習慣が睡眠の質を低下させている」と明記されています。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n近年、プラスチックごみによる海洋汚染が深刻な問題となっている。海に流れ込んだプラスチックは、海洋生物に飲み込まれたり、船のエンジンに絡まったりするなど、様々な被害を引き起こしている。また、プラスチックは自然に分解されるのに何百年もかかるため、一度海に入ってしまうと長期間残り続ける。この問題を解決するために、多くの国がレジ袋の有料化やプラスチックストローの使用禁止などの対策を取り始めている。しかし、個人レベルでも、マイバッグを持参したり、使い捨て製品の使用を減らしたりするなど、日常生活での意識的な行動が求められている。',
        "question": 'プラスチックの問題として文章に書かれていないものはどれですか？',
        "option_a": '海洋生物が飲み込む',
        "option_b": '船のエンジンに絡まる',
        "option_c": 'プラスチックの製造コストが高い',
        "option_d": '自然分解に何百年もかかる',
        "correct_answer": 'c',
        "explanation": '文章では「製造コスト」については触れていません。記載されている問題は a・b・d の三点です。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n日本の教育システムは、近年大きな変化を遂げている。従来の暗記中心の教育から、思考力や創造性を重視する教育へのシフトが進んでいる。文部科学省は「生きる力」という概念を打ち出し、知識だけでなく、問題解決能力やコミュニケーション能力を育てることを目標としている。また、グローバル化に対応するため、英語教育の強化も図られており、小学校から英語を必修科目として教えることが義務付けられた。一方で、このような改革に対して、教師の負担増加や、基礎学力の低下を懸念する声もある。教育改革は一朝一夕には実現できないが、子どもたちの未来のために継続的な取り組みが必要とされている。',
        "question": '文章の内容として正しいものはどれですか？',
        "option_a": '日本では暗記中心の教育が今も続いている',
        "option_b": '小学校から英語が必修科目になった',
        "option_c": '教育改革はすでに完成した',
        "option_d": '教師の数が増加している',
        "correct_answer": 'b',
        "explanation": '「小学校から英語を必修科目として教えることが義務付けられた」と明記されています。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題1】「戦後、日本は＿貧しい＿時代を経験した。」下線部の読み方として最もよいものはどれですか。',
        "option_a": 'まずしい',
        "option_b": 'きびしい',
        "option_c": 'けわしい',
        "option_d": 'はげしい',
        "correct_answer": 'a',
        "explanation": '貧しい（まずしい）＝ 貧窮、困乏。「乏しい」（とぼしい）と混同しないように。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題1】「この黒い＿種＿からどんな花がさくのだろうか。」下線部の読み方として最もよいものはどれですか。',
        "option_a": 'だね',
        "option_b": 'たね',
        "option_c": 'じゅ',
        "option_d": 'しゅ',
        "correct_answer": 'b',
        "explanation": '種（たね）＝ 種子。「種類」（しゅるい）のように音読みでは「しゅ」だが、単独では訓読み「たね」。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題2】「今日は、ごみの＿しゅうしゅう＿日ですか。」下線部を漢字で書くとき最もよいものはどれですか。',
        "option_a": '拾集',
        "option_b": '修集',
        "option_c": '取集',
        "option_d": '収集',
        "correct_answer": 'd',
        "explanation": '収集（しゅうしゅう）＝ 集めること。「収」は「おさめる」、「集」は「あつめる」。ごみの収集日（ゴミの回収日）。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題2】「このカメラはデザインも性能も＿すぐれて＿いる。」下線部を漢字で書くとき最もよいものはどれですか。',
        "option_a": '超れて',
        "option_b": '恵れて',
        "option_c": '秀れて',
        "option_d": '優れて',
        "correct_answer": 'd',
        "explanation": '優れている（すぐれている）＝ 出色、卓越。「優」は「やさしい・すぐれる」。「秀れる」は誤字（「秀でる」が正しい）。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題3】「新しい商品を売るために、彼は毎日忙しく飛び（\u3000）いる。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'かかって',
        "option_b": 'かけて',
        "option_c": 'まわって',
        "option_d": 'まわして',
        "correct_answer": 'c',
        "explanation": '「飛び回っている」＝ 到處奔走。「飛びかかる」是撲上去，「飛び回る」才是四處奔跑的意思。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題3】「あの映画の最後は（\u3000）場面として知られている。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": '名',
        "option_b": '高',
        "option_c": '良',
        "option_d": '真',
        "correct_answer": 'a',
        "explanation": '「名場面（めいばめん）」＝ 名場景、令人印象深刻的場景。「名」作前綴表示「著名的・精彩的」。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題4】「日本人の平均（\u3000）は、男性が79歳、女性が86歳である。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": '生命',
        "option_b": '寿命',
        "option_c": '人生',
        "option_d": '一生',
        "correct_answer": 'b',
        "explanation": '「平均寿命（へいきんじゅみょう）」＝ 平均壽命。固定搭配，其他選項不與「平均」搭配。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題4】「CDの売り上げは3年（\u3000）で減少しているそうだ。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": '連続',
        "option_b": '接続',
        "option_c": '持続',
        "option_d": '相続',
        "correct_answer": 'a',
        "explanation": '「3年連続（れんぞく）で」＝ 連續3年。「接続」是連接、「持続」是持續、「相続」是繼承，均不符合。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題5】「田中さんは＿単なる＿友人です。」下線部の言葉に意味が最も近いものはどれですか。',
        "option_a": '大切な',
        "option_b": '一生の',
        "option_c": 'ただの',
        "option_d": '唯一の',
        "correct_answer": 'c',
        "explanation": '「単なる（たんなる）」＝ 只是、不過是。等同於「ただの」。「唯一の」強調獨一無二，語意不同。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題5】「あの人のお母さんはいつも＿ほがらか＿です。」下線部の言葉に意味が最も近いものはどれですか。',
        "option_a": 'おとなしい',
        "option_b": 'まじめ',
        "option_c": 'りっぱ',
        "option_d": 'あかるい',
        "correct_answer": 'd',
        "explanation": '「ほがらか」＝ 開朗、爽朗，近似「明るい（あかるい）」。「おとなしい」是溫順，「まじめ」是認真，語意不同。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題6】次の「余計」の言葉の使い方として最もよいものはどれですか。',
        "option_a": '一人暮らしだと野菜がすぐ余計になってしまう。',
        "option_b": '話が複雑になるから、余計なことは言わないで。',
        "option_c": '余計があったら、ひとつ貸してもらえませんか。',
        "option_d": 'このごろ仕事が忙しくて、遊びに行く余計がない。',
        "correct_answer": 'b',
        "explanation": '「余計な（よけいな）」＝ 多餘的、不必要的。「余計なことを言う」是固定用法。選項a應用「余る」、c應用「余り」、d應用「余裕（よゆう）」。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '【問題6】次の「率直」の言葉の使い方として最もよいものはどれですか。',
        "option_a": 'あの人は率直に仕事をしているので、評判がいい。',
        "option_b": 'この申込書にはあなたの住所を率直に書いてください。',
        "option_c": 'このアンケートには、皆様のご意見を率直にお書きください。',
        "option_d": 'お客様からの苦情には率直に対応する必要がある。',
        "correct_answer": 'c',
        "explanation": '「率直に（そっちょくに）」＝ 坦率地、直率地表達意見。選項a應用「真剣に」、b應用「正確に」、d應用「誠実に」。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '【問題7】「最終のバスに間に合わなくて困っていた（\u3000）、運よくタクシーが通りかかり、無事帰宅できた。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'あげくに',
        "option_b": 'ために',
        "option_c": 'とたんに',
        "option_d": 'ところに',
        "correct_answer": 'd',
        "explanation": '「～ていたところに」＝ 就在那個時候（某事發生）。表示正好在某個狀態時，偶然發生了別的事。「あげくに」是最後終於、「とたんに」是一瞬間，均不符合語意。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '【問題7】「親が他人をいつも（\u3000）子どもも人をうらやむようになるというのが父の口癖だった。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'うらやんでばかりいると',
        "option_b": 'うらやんでばかりいても',
        "option_c": 'うらやんだだけだと',
        "option_d": 'うらやんだだけでも',
        "correct_answer": 'a',
        "explanation": '「～ていると（そうなる）」＝ 如果一直做某事，就會…（條件・因果）。「ばかりいる」強調持續狀態，接「と」表示自然結果。',
    },
    {
        "type": 'grammar',
        "context": '【問題8】次の文の＿★＿に入る最もよいものを選ぶ問題です。4つの語句を正しい順に並べ替えて、★の位置に来る語句を答えてください。\n\n文：「ふだん感情を表に出さない彼があんなに ___ ___ ★ ___ ほど良いことがあったのだろう。」\n【語句】1 みると\u30002 ところを\u30003 いる\u30004 喜んで\n【正しい語順】喜んで(4) → いる(3) → ところを(2) → みると(1)',
        "question": '★の位置（3番目）に入る語句はどれですか。',
        "option_a": 'みると',
        "option_b": 'ところを',
        "option_c": 'いる',
        "option_d": '喜んで',
        "correct_answer": 'b',
        "explanation": '正しい語順：「彼があんなに 喜んで いる ところを みると ほど良いことがあったのだろう」。★は3番目の位置なので「ところを」。',
    },
    {
        "type": 'grammar',
        "context": '【問題8】次の文の＿★＿に入る最もよいものを選ぶ問題です。4つの語句を正しい順に並べ替えて、★の位置に来る語句を答えてください。\n\n文：「田中選手が今シーズン ___ ★ ___ ___ のニュースを見て驚いた。」\n【語句】1 彼の怪我\u30002 活躍するのを\u30003 楽しみに待っていた\u30004 だけに\n【正しい語順】活躍するのを(2) → 楽しみに待っていた(3) → だけに(4) → 彼の怪我(1)',
        "question": '★の位置（2番目）に入る語句はどれですか。',
        "option_a": '彼の怪我',
        "option_b": '活躍するのを',
        "option_c": '楽しみに待っていた',
        "option_d": 'だけに',
        "correct_answer": 'c',
        "explanation": '正しい語順：「今シーズン 活躍するのを 楽しみに待っていた だけに 彼の怪我 のニュースを見て驚いた」。★は2番目なので「楽しみに待っていた」。「～だけに」＝ 正因為如此（所以更令人驚訝）。',
    },
    {
        "type": 'grammar',
        "context": '【問題文】\n\u3000街にはおもちゃがあふれています。贈り物におもちゃを買おうと思っても、おもちゃ屋に並ぶ多種多様なおもちゃの前でどれを選んだらいいか迷ってしまったという方もいるかもしれません。\n\u3000そこで、ある団体が、おもちゃを選ぶ時の参考にしてもらおうと、毎年、[17]の中から優良なおもちゃ、「グッド・トイ」を選定しています。お店で見てすぐにわかるように、選定されたグッド・トイには[18]ので、おもちゃを買うときにも参考になります。\n\u3000グッド・トイ[19]「遊び力」を引き出してくれるものだそうです。「遊び力」というのは、見る力、聞く力、感じる力、コミュニケーションする力、夢見る力。人が生きていくのに必要な力のことです。\n\u3000グッド・トイの選考では、まず推薦されたおもちゃをいろいろな年代の人に実際に遊んでみてもらい、専門家が遊ばれ方を見て評価をします。その後も様々な視点から何度も検討を重ねてグッド・トイは選定されています。\n\u3000おもちゃというと、ただ子どもが遊ぶためだけのものだと[20]。塾や参考書は熱心に選んでも、おもちゃを真剣に選ぶという方はあまり多くないのではないでしょうか。\n\u3000[21]、おもちゃには大きな力を持つものがあります。次におもちゃを選ぶ時は、グッド・トイのように、生きる力を引き出してくれるものを探してみてはいかがでしょうか。',
        "question": '【問題9】文章中の[17]に入れるのに最もよいものはどれですか。',
        "option_a": 'たくさんの贈り物',
        "option_b": '選んだ贈り物',
        "option_c": '数あるおもちゃ',
        "option_d": '迷ったおもちゃ',
        "correct_answer": 'c',
        "explanation": '「数あるおもちゃの中から優良なものを選定する」＝ 從眾多玩具中選出優良的。「数ある」是「很多的、為數眾多的」之意。',
    },
    {
        "type": 'grammar',
        "context": '【問題文】\n\u3000街にはおもちゃがあふれています。贈り物におもちゃを買おうと思っても、おもちゃ屋に並ぶ多種多様なおもちゃの前でどれを選んだらいいか迷ってしまったという方もいるかもしれません。\n\u3000そこで、ある団体が、おもちゃを選ぶ時の参考にしてもらおうと、毎年、[17]の中から優良なおもちゃ、「グッド・トイ」を選定しています。お店で見てすぐにわかるように、選定されたグッド・トイには[18]ので、おもちゃを買うときにも参考になります。\n\u3000グッド・トイ[19]「遊び力」を引き出してくれるものだそうです。「遊び力」というのは、見る力、聞く力、感じる力、コミュニケーションする力、夢見る力。人が生きていくのに必要な力のことです。\n\u3000グッド・トイの選考では、まず推薦されたおもちゃをいろいろな年代の人に実際に遊んでみてもらい、専門家が遊ばれ方を見て評価をします。その後も様々な視点から何度も検討を重ねてグッド・トイは選定されています。\n\u3000おもちゃというと、ただ子どもが遊ぶためだけのものだと[20]。塾や参考書は熱心に選んでも、おもちゃを真剣に選ぶという方はあまり多くないのではないでしょうか。\n\u3000[21]、おもちゃには大きな力を持つものがあります。次におもちゃを選ぶ時は、グッド・トイのように、生きる力を引き出してくれるものを探してみてはいかがでしょうか。',
        "question": '【問題9】文章中の[18]に入れるのに最もよいものはどれですか。',
        "option_a": 'グッド・トイマークがつけられていきました',
        "option_b": 'グッド・トイマークがつけられています',
        "option_c": 'グッド・トイマークをつけておきました',
        "option_d": 'グッド・トイマークをつけてみます',
        "correct_answer": 'b',
        "explanation": '「選定されたグッド・トイにはグッド・トイマークがつけられています」＝ 被貼上標章（現在的狀態）。用被動+ている表示現狀。',
    },
    {
        "type": 'grammar',
        "context": '【問題文】\n\u3000街にはおもちゃがあふれています。贈り物におもちゃを買おうと思っても、おもちゃ屋に並ぶ多種多様なおもちゃの前でどれを選んだらいいか迷ってしまったという方もいるかもしれません。\n\u3000そこで、ある団体が、おもちゃを選ぶ時の参考にしてもらおうと、毎年、[17]の中から優良なおもちゃ、「グッド・トイ」を選定しています。お店で見てすぐにわかるように、選定されたグッド・トイには[18]ので、おもちゃを買うときにも参考になります。\n\u3000グッド・トイ[19]「遊び力」を引き出してくれるものだそうです。「遊び力」というのは、見る力、聞く力、感じる力、コミュニケーションする力、夢見る力。人が生きていくのに必要な力のことです。\n\u3000グッド・トイの選考では、まず推薦されたおもちゃをいろいろな年代の人に実際に遊んでみてもらい、専門家が遊ばれ方を見て評価をします。その後も様々な視点から何度も検討を重ねてグッド・トイは選定されています。\n\u3000おもちゃというと、ただ子どもが遊ぶためだけのものだと[20]。塾や参考書は熱心に選んでも、おもちゃを真剣に選ぶという方はあまり多くないのではないでしょうか。\n\u3000[21]、おもちゃには大きな力を持つものがあります。次におもちゃを選ぶ時は、グッド・トイのように、生きる力を引き出してくれるものを探してみてはいかがでしょうか。',
        "question": '【問題9】文章中の[19]に入れるのに最もよいものはどれですか。',
        "option_a": 'が',
        "option_b": 'に',
        "option_c": 'とか',
        "option_d": 'とは',
        "correct_answer": 'd',
        "explanation": '「グッド・トイとは『遊び力』を引き出してくれるものだ」＝ 所謂的「好玩具」是指…。「とは」用於定義或解釋名詞。',
    },
    {
        "type": 'grammar',
        "context": '【問題文】\n\u3000街にはおもちゃがあふれています。贈り物におもちゃを買おうと思っても、おもちゃ屋に並ぶ多種多様なおもちゃの前でどれを選んだらいいか迷ってしまったという方もいるかもしれません。\n\u3000そこで、ある団体が、おもちゃを選ぶ時の参考にしてもらおうと、毎年、[17]の中から優良なおもちゃ、「グッド・トイ」を選定しています。お店で見てすぐにわかるように、選定されたグッド・トイには[18]ので、おもちゃを買うときにも参考になります。\n\u3000グッド・トイ[19]「遊び力」を引き出してくれるものだそうです。「遊び力」というのは、見る力、聞く力、感じる力、コミュニケーションする力、夢見る力。人が生きていくのに必要な力のことです。\n\u3000グッド・トイの選考では、まず推薦されたおもちゃをいろいろな年代の人に実際に遊んでみてもらい、専門家が遊ばれ方を見て評価をします。その後も様々な視点から何度も検討を重ねてグッド・トイは選定されています。\n\u3000おもちゃというと、ただ子どもが遊ぶためだけのものだと[20]。塾や参考書は熱心に選んでも、おもちゃを真剣に選ぶという方はあまり多くないのではないでしょうか。\n\u3000[21]、おもちゃには大きな力を持つものがあります。次におもちゃを選ぶ時は、グッド・トイのように、生きる力を引き出してくれるものを探してみてはいかがでしょうか。',
        "question": '【問題9】文章中の[20]に入れるのに最もよいものはどれですか。',
        "option_a": '考えられつつあります',
        "option_b": '考えられがちです',
        "option_c": '考えられてはいません',
        "option_d": '考えられなければいけません',
        "correct_answer": 'b',
        "explanation": '「～がちです」＝ 往往容易變成…、容易傾向於…。「おもちゃは子どものものと考えられがちだ」＝ 人們往往認為玩具只是給孩子的。',
    },
    {
        "type": 'grammar',
        "context": '【問題文】\n\u3000街にはおもちゃがあふれています。贈り物におもちゃを買おうと思っても、おもちゃ屋に並ぶ多種多様なおもちゃの前でどれを選んだらいいか迷ってしまったという方もいるかもしれません。\n\u3000そこで、ある団体が、おもちゃを選ぶ時の参考にしてもらおうと、毎年、[17]の中から優良なおもちゃ、「グッド・トイ」を選定しています。お店で見てすぐにわかるように、選定されたグッド・トイには[18]ので、おもちゃを買うときにも参考になります。\n\u3000グッド・トイ[19]「遊び力」を引き出してくれるものだそうです。「遊び力」というのは、見る力、聞く力、感じる力、コミュニケーションする力、夢見る力。人が生きていくのに必要な力のことです。\n\u3000グッド・トイの選考では、まず推薦されたおもちゃをいろいろな年代の人に実際に遊んでみてもらい、専門家が遊ばれ方を見て評価をします。その後も様々な視点から何度も検討を重ねてグッド・トイは選定されています。\n\u3000おもちゃというと、ただ子どもが遊ぶためだけのものだと[20]。塾や参考書は熱心に選んでも、おもちゃを真剣に選ぶという方はあまり多くないのではないでしょうか。\n\u3000[21]、おもちゃには大きな力を持つものがあります。次におもちゃを選ぶ時は、グッド・トイのように、生きる力を引き出してくれるものを探してみてはいかがでしょうか。',
        "question": '【問題9】文章中の[21]に入れるのに最もよいものはどれですか。',
        "option_a": 'しかし',
        "option_b": 'それどころか',
        "option_c": 'すなわち',
        "option_d": 'さらに',
        "correct_answer": 'a',
        "explanation": '「しかし、おもちゃには大きな力を持つものがあります」＝ 然而，玩具中也有具有強大力量的。前文說人們往往不重視玩具，此處用「しかし」轉折，指出玩具其實很重要。',
    },
    {
        "type": 'reading',
        "context": '【問題文】（前略）「仕事ができる人」と「できない人」のいちばんの違いは何だろうか。私がいろいろな仕事で接してきた「できる人」に共通している特徴は、「自分の能力特性の分析」がうまいということだ。\n\u3000まず、自分は何が得意で、何が不得意なのかを分かっている。もちろんオールマイティ（注1）にあらゆる仕事をこなす（注2）エリートもいるのだろうが、たいていの人は、「仕事の得手、不得手」を持っている。そのうえで、「得意な仕事」を積極的にこなし、「不得意な仕事」からは上手に逃げている人が、実は「仕事ができる人」と評価されるのだ。\n（和田秀樹『頭をよくする ちょっとした「習慣術」』による）\n（注1）オールマイティ：どんなことも完全にできること\u3000（注2）こなす：処理する',
        "question": '【問題10】この筆者から見た「仕事ができる人」の特徴はどんなことか。',
        "option_a": '自分に向いている仕事は一生懸命やり、向いていない仕事からはうまく逃げること',
        "option_b": '自分の能力特性を高めるための努力をいつも忘れず、何にでも積極的に取り組むこと',
        "option_c": 'オールマイティに仕事をしている人のやり方を見習い、不得意なことを克服すること',
        "option_d": '始めに仕事が自分の能力に合っているかを分析し、あらゆる仕事を上手にこなすこと',
        "correct_answer": 'a',
        "explanation": '文章中明確指出：「得意な仕事を積極的にこなし、不得意な仕事からは上手に逃げている人が、実は仕事ができる人」。選項b、c、d與文意相反或過度延伸。',
    },
    {
        "type": 'reading',
        "context": '【問題文】下の文章は、企業のあり方についての本を出版した人が、その本の内容を紹介したものである。\n\u3000最近、企業の不祥事（注1）が相次いでいますが、問題を起こす企業には共通点があると思います。それは「社員を大切にしていない」ということです。「社員を大切にする」とは、給料が高いとか、福利厚生（注2）を充実させるということではなく、仕事を通じて成長できるとか、仲間と協力して物事を成し遂げる達成感が感じられるといったことです。問題のある企業はこれらをないがしろ（注3）にし、利益だけしか見ていないのです。\n\u3000ただ、ここ数年、社員を大切にしながらも業績（注4）を上げている企業が増えています。「社員を大切にするなどと甘いことを言っていたら、経営は成り立たない」と言われる中で、なぜ①それが可能なのか。その条件を探ることが、本書の執筆理由です。\n\u3000そこで一つ明らかになったのは、通常とは異なるリーダーの姿です。多くの場合、非常に優れたリーダーがいて、社員はただ従っていれば業績が良くなるということが想定されますが、社員を大切にしながら業績を上げる企業のリーダーはそうではなく、社員を主役にするのです。私はこれをスポンサーシップと名付けましたが、そこでは社員がどんどん力をつけ、育っていきます。\n（柴田昌治「リーダーシップからスポンサーシップへ」『フォーブス』2007年9月号による）\n（注1）不祥事：社会に迷惑をかけるような失敗や間違い\u3000（注2）福利厚生：企業が従業員やその家族のためになるように作った制度や施設\u3000（注3）ないがしろ：軽く考えること\u3000（注4）業績：仕事の成果や実績',
        "question": '【問題11】①それは何を指しているか。',
        "option_a": '問題を起こしても経営を成り立たせること',
        "option_b": '高い給料を払って、福祉を充実させること',
        "option_c": '社員が仲間と協力して仕事を達成すること',
        "option_d": '社員を大切にしながらも業績を上げること',
        "correct_answer": 'd',
        "explanation": '①それの直前：「社員を大切にしながらも業績を上げている企業が増えています…なぜ①それが可能なのか」→ 「それ」指的是「社員を大切にしながら業績を上げること」。',
    },
    {
        "type": 'reading',
        "context": '【問題文】下の文章は、企業のあり方についての本を出版した人が、その本の内容を紹介したものである。\n\u3000最近、企業の不祥事（注1）が相次いでいますが、問題を起こす企業には共通点があると思います。それは「社員を大切にしていない」ということです。「社員を大切にする」とは、給料が高いとか、福利厚生（注2）を充実させるということではなく、仕事を通じて成長できるとか、仲間と協力して物事を成し遂げる達成感が感じられるといったことです。問題のある企業はこれらをないがしろ（注3）にし、利益だけしか見ていないのです。\n\u3000ただ、ここ数年、社員を大切にしながらも業績（注4）を上げている企業が増えています。「社員を大切にするなどと甘いことを言っていたら、経営は成り立たない」と言われる中で、なぜ①それが可能なのか。その条件を探ることが、本書の執筆理由です。\n\u3000そこで一つ明らかになったのは、通常とは異なるリーダーの姿です。多くの場合、非常に優れたリーダーがいて、社員はただ従っていれば業績が良くなるということが想定されますが、社員を大切にしながら業績を上げる企業のリーダーはそうではなく、社員を主役にするのです。私はこれをスポンサーシップと名付けましたが、そこでは社員がどんどん力をつけ、育っていきます。\n（柴田昌治「リーダーシップからスポンサーシップへ」『フォーブス』2007年9月号による）\n（注1）不祥事：社会に迷惑をかけるような失敗や間違い\u3000（注2）福利厚生：企業が従業員やその家族のためになるように作った制度や施設\u3000（注3）ないがしろ：軽く考えること\u3000（注4）業績：仕事の成果や実績',
        "question": '【問題11】筆者がここで重視している「企業の優れたリーダー」とは、どのようなリーダーか。',
        "option_a": '強い指導力で社員を引っぱり、どんどん業績を上げることのできるリーダー',
        "option_b": '社員に高い給料を払い、福利厚生を充実させることを第一に考えるリーダー',
        "option_c": '社員の自主性を尊重し、社員が働きながら伸びていけるようにするリーダー',
        "option_d": '教育に十分時間をかけ、社員が成長してから働いてもらおうとするリーダー',
        "correct_answer": 'c',
        "explanation": '文章：「社員を主役にするのです…社員がどんどん力をつけ、育っていきます」→ 讓員工自主發展的領導者。選項a（強力統帥）與文意相反。',
    },
    {
        "type": 'reading',
        "context": '【相談者】\n\u3000私の彼のことで相談したいことがあります。彼は私の誕生日などによくセーターやアクセサリーをプレゼントしてくれるのですが、いつも私の好みではないものを贈ってくれるのです。私はどちらかというと単色ではっきりした色のシャープなデザインのものが好みなのですが、彼からのプレゼントはいつも淡い色を多く使った、女の子らしいかわいいデザインのものが多いのです。\n\u3000彼のことはとても好きだし、一生懸命選んでくれているのがわかるだけに、①私の本当の気持ちを言い出しにくくて困っています。どうしたらよいでしょうか。\n\n【回答者：A】\n\u3000これからも長くお付き合いすることを考えているのなら、やはり彼にあなたの本当の好みを伝えて分かってもらったほうがよいと思います。でもプレゼントをもらった時に「こういうのは好きじゃない」と言うと彼を傷つけてしまうので、ふだんからデートの時にショーウィンドーなどを見ながら、「わたしこんな服が好きなのよ」とか「これ、欲しいなあ」などと言って、彼にそれとなく伝えるようにしてはいかがでしょうか。\n\n【回答者：B】\n\u3000自分で思っているイメージと他人から見たイメージとは違っていることも多いものです。自分では「シャープなデザインが似合う」と思っていても、彼から見ると「かわいらしい感じのデザインが似合うはず」と思っているのかもしれません。自分で自分のイメージを決めてしまわずに、一度思い切って身につけてみてはどうでしょうか。新しい自分が発見できるかもしれませんし、彼もそれを期待しているのかもしれませんよ。',
        "question": '【問題12】①私の本当の気持ちとは、どんな気持ちか。',
        "option_a": '彼が一生懸命選んでくれているのでとてもうれしい。',
        "option_b": '彼からのプレゼントは私の好みのものでない。',
        "option_c": '淡い色のかわいらしいデザインのものが欲しい。',
        "option_d": 'セーターやアクセサリーはもうあまり欲しくない。',
        "correct_answer": 'b',
        "explanation": '相談文：「いつも私の好みではないものを贈ってくれる」「私の本当の気持ちを言い出しにくくて」→ 本當的心情是「他的禮物不合我的喜好」。',
    },
    {
        "type": 'reading',
        "context": '【相談者】\n\u3000私の彼のことで相談したいことがあります。彼は私の誕生日などによくセーターやアクセサリーをプレゼントしてくれるのですが、いつも私の好みではないものを贈ってくれるのです。私はどちらかというと単色ではっきりした色のシャープなデザインのものが好みなのですが、彼からのプレゼントはいつも淡い色を多く使った、女の子らしいかわいいデザインのものが多いのです。\n\u3000彼のことはとても好きだし、一生懸命選んでくれているのがわかるだけに、①私の本当の気持ちを言い出しにくくて困っています。どうしたらよいでしょうか。\n\n【回答者：A】\n\u3000これからも長くお付き合いすることを考えているのなら、やはり彼にあなたの本当の好みを伝えて分かってもらったほうがよいと思います。でもプレゼントをもらった時に「こういうのは好きじゃない」と言うと彼を傷つけてしまうので、ふだんからデートの時にショーウィンドーなどを見ながら、「わたしこんな服が好きなのよ」とか「これ、欲しいなあ」などと言って、彼にそれとなく伝えるようにしてはいかがでしょうか。\n\n【回答者：B】\n\u3000自分で思っているイメージと他人から見たイメージとは違っていることも多いものです。自分では「シャープなデザインが似合う」と思っていても、彼から見ると「かわいらしい感じのデザインが似合うはず」と思っているのかもしれません。自分で自分のイメージを決めてしまわずに、一度思い切って身につけてみてはどうでしょうか。新しい自分が発見できるかもしれませんし、彼もそれを期待しているのかもしれませんよ。',
        "question": '【問題12】「相談者」の相談に対するA、Bの回答について、正しいのはどれか。',
        "option_a": 'AもBも、彼からの心のこもったプレゼントなので、素直に身につけたほうがよいと言っている。',
        "option_b": 'AもBも、長くお付き合いするために相手の好みや考え方に合わせるべきだと言っている。',
        "option_c": 'Aは相談者の彼の考え方に理解を示し、Bは相談者の好みをより重視する意見を述べている。',
        "option_d": 'Aは相談者の好みをより重視し、Bは相談者の彼の考え方に理解を示す意見を述べている。',
        "correct_answer": 'd',
        "explanation": 'A：建議將真實喜好告訴對方（重視相談者的喜好）。B：建議試著穿他選的東西，因為他人看我們的形象可能不同（理解男友的觀點）。→ 選項d正確。',
    },
    {
        "type": 'reading',
        "context": '【問題文】（前略）「自分を変える」と言いながら一切（注1）変わらない人は、実は毎日の生き方の中に自分の基準を持っていないのではないだろうか。\n\u3000肝心（注2）なのは、まわりの評価ではなく、自分自身の基準で生きていくことではないかと思う。たとえば私は毎朝ジョギングをするのだが、道すがら（注3）「今日はよく走れた、昨日よりペースが上がった」など、自分の中で勝負している。仕事にしても何にしても、それに打ち込む（注4）姿勢がスリリング（注5）で、②われわれ自身の「ゲーム」になっているのではないか。\n\u3000つまり①「自分を変える」ということは、まわりの評価や社会通念上の勝ち負けに関係なく、毎日の生き方の中に自分の基準を持つことなのではないだろうか。成功とは、自分が本当に満足できる生き方のことではないかと私は思う。\n（注1）一切：すべて\u3000（注2）肝心の：もっとも重要な\u3000（注3）道すがら：途中で\u3000（注4）打ち込む：何かをいっしょうけんめいする\u3000（注5）スリリング：わくわくすること',
        "question": '【問題13】①「自分を変える」こととは、どのようにすることか。',
        "option_a": '自分が本当にやりたかった職業につくこと',
        "option_b": '負けた時にも成功だと思える人になること',
        "option_c": '毎日の生き方の中に自分の基準を持つこと',
        "option_d": 'まわりの評価を基準にする人間になること',
        "correct_answer": 'c',
        "explanation": '文章：「①『自分を変える』ということは、まわりの評価や社会通念上の勝ち負けに関係なく、毎日の生き方の中に自分の基準を持つことなのではないだろうか」→ 直接對應選項c。',
    },
    {
        "type": 'reading',
        "context": '【問題文】（前略）「自分を変える」と言いながら一切（注1）変わらない人は、実は毎日の生き方の中に自分の基準を持っていないのではないだろうか。\n\u3000肝心（注2）なのは、まわりの評価ではなく、自分自身の基準で生きていくことではないかと思う。たとえば私は毎朝ジョギングをするのだが、道すがら（注3）「今日はよく走れた、昨日よりペースが上がった」など、自分の中で勝負している。仕事にしても何にしても、それに打ち込む（注4）姿勢がスリリング（注5）で、②われわれ自身の「ゲーム」になっているのではないか。\n\u3000つまり①「自分を変える」ということは、まわりの評価や社会通念上の勝ち負けに関係なく、毎日の生き方の中に自分の基準を持つことなのではないだろうか。成功とは、自分が本当に満足できる生き方のことではないかと私は思う。\n（注1）一切：すべて\u3000（注2）肝心の：もっとも重要な\u3000（注3）道すがら：途中で\u3000（注4）打ち込む：何かをいっしょうけんめいする\u3000（注5）スリリング：わくわくすること',
        "question": '【問題13】②われわれ自身の「ゲーム」が意味していることは何か。',
        "option_a": '自分の生き方や生活',
        "option_b": 'ジョギング中の発見',
        "option_c": '成功の基準を探すこと',
        "option_d": '自分に合っている仕事',
        "correct_answer": 'a',
        "explanation": '文章：「それに打ち込む姿勢がスリリングで、②われわれ自身の『ゲーム』になっているのではないか」→ 「ゲーム」比喻的是「自分の生き方・日常生活そのもの」。',
    },
    {
        "type": 'reading',
        "context": '【問題文】（前略）「自分を変える」と言いながら一切（注1）変わらない人は、実は毎日の生き方の中に自分の基準を持っていないのではないだろうか。\n\u3000肝心（注2）なのは、まわりの評価ではなく、自分自身の基準で生きていくことではないかと思う。たとえば私は毎朝ジョギングをするのだが、道すがら（注3）「今日はよく走れた、昨日よりペースが上がった」など、自分の中で勝負している。仕事にしても何にしても、それに打ち込む（注4）姿勢がスリリング（注5）で、②われわれ自身の「ゲーム」になっているのではないか。\n\u3000つまり①「自分を変える」ということは、まわりの評価や社会通念上の勝ち負けに関係なく、毎日の生き方の中に自分の基準を持つことなのではないだろうか。成功とは、自分が本当に満足できる生き方のことではないかと私は思う。\n（注1）一切：すべて\u3000（注2）肝心の：もっとも重要な\u3000（注3）道すがら：途中で\u3000（注4）打ち込む：何かをいっしょうけんめいする\u3000（注5）スリリング：わくわくすること',
        "question": '【問題13】筆者がこの文章で一番言いたいことはどんなことか。',
        "option_a": 'まわりの評価を基準にしたとき自分の生き方が成功だったとしても、自分が本当に満足していなければ成功とは言えない。',
        "option_b": 'まわりの基準による勝ち負けの発想を捨て、自分で決めた成功基準を自分の行動に当てはめて生活することが大切である。',
        "option_c": '人生で勝ち組に入るにはまわりの評価や基準を気にせず、世界共通の基準を意識して自分の中に取り入れるべきである。',
        "option_d": '一日の生き方で大切なことは、朝早く起き、適度な運動をし、気持ちよく仕事をし、夜仲間と楽しくつきあうことである。',
        "correct_answer": 'b',
        "explanation": '筆者主旨：放棄「被他人標準評判的勝負」觀念，以自己決定的成功基準生活。選項a只說了「不滿足就不算成功」，沒有點出「用自己基準生活」的積極面。選項c扭曲了原意（作者並非建議參考世界共通標準）。',
    },
    {
        "type": 'reading',
        "context": '【かすみ市立図書館利用案内】\n★図書館カードの新規作成\n※図書やCD等の資料を借りるには図書館カードが必要です。\n\nあなたは、かすみ市にお住まいですか？\n\u3000→ はい：図書館カードが作れます。\n\u3000\u3000運転免許証、健康保険証、自分あての郵便物など現住所が確認できるものをお持ちください。外国人の方で6か月以上滞在の場合は外国人登録証があればカードが作れます。\n\u3000→ いいえ：あなたは、かすみ市に通勤または通学していますか？\n\u3000\u3000→ はい：図書館カードが作れます。\n\u3000\u3000\u3000上記の現住所が確認できるものに加えて、学生証、社員証など通勤・通学が確認できるものをお持ちください。\n\u3000\u3000→ いいえ：図書館カードは作れませんが、館内での図書の利用は可能です。\n\n★図書館カードの更新\n図書館カードの有効期限は3年間です。有効期限が過ぎる前に、カードの更新をしてください。\n更新に必要なもの：古いカードおよび新規申込時と同様の証明書をお持ちください。\n※古いカードで借りたまま返していない貸し出し図書がある場合は更新できません。\n\n★貸し出し冊数\n図書（本・雑誌）\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u30001人5冊まで\nCD・カセットテープ・ビデオテープ・DVD\u30001人3点まで\n合計8点まで貸し出しできます。\n※ただし、雑誌の最新号は貸し出しできません。\n\n★貸し出し期間\n図書（本・雑誌）\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u30002週間以内\nCD・カセットテープ・ビデオテープ・DVD\u30001週間以内\n※貸し出し期間の算定は、貸し出し日の翌日からとなります。\n※貸し出し期間は、申し込みのあった日から2週間だけ延長することができます。\n\u3000電話でのお申し込みも受け付けます。\n\u3000（ただし、期限切れや予約が入っている図書の延長はできません。また、CDやビデオなどの視聴覚資料の延長はできませんのでご了承ください。）',
        "question": '【問題14】かすみ市に住んではいないが市内で働いている人が、図書館カードを作るとき何が必要か。',
        "option_a": '現住所が確認できるもの',
        "option_b": '通勤・通学が確認できるもの',
        "option_c": '現住所と通勤が確認できるもの',
        "option_d": '現住所が確認できるものと外国人登録証',
        "correct_answer": 'c',
        "explanation": '利用案内：市外居住者で通勤者の場合「上記の現住所が確認できるものに加えて、社員証など通勤・通学が確認できるもの」が必要。→ 兩者都需要。',
    },
    {
        "type": 'reading',
        "context": '【かすみ市立図書館利用案内】\n★図書館カードの新規作成\n※図書やCD等の資料を借りるには図書館カードが必要です。\n\nあなたは、かすみ市にお住まいですか？\n\u3000→ はい：図書館カードが作れます。\n\u3000\u3000運転免許証、健康保険証、自分あての郵便物など現住所が確認できるものをお持ちください。外国人の方で6か月以上滞在の場合は外国人登録証があればカードが作れます。\n\u3000→ いいえ：あなたは、かすみ市に通勤または通学していますか？\n\u3000\u3000→ はい：図書館カードが作れます。\n\u3000\u3000\u3000上記の現住所が確認できるものに加えて、学生証、社員証など通勤・通学が確認できるものをお持ちください。\n\u3000\u3000→ いいえ：図書館カードは作れませんが、館内での図書の利用は可能です。\n\n★図書館カードの更新\n図書館カードの有効期限は3年間です。有効期限が過ぎる前に、カードの更新をしてください。\n更新に必要なもの：古いカードおよび新規申込時と同様の証明書をお持ちください。\n※古いカードで借りたまま返していない貸し出し図書がある場合は更新できません。\n\n★貸し出し冊数\n図書（本・雑誌）\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u30001人5冊まで\nCD・カセットテープ・ビデオテープ・DVD\u30001人3点まで\n合計8点まで貸し出しできます。\n※ただし、雑誌の最新号は貸し出しできません。\n\n★貸し出し期間\n図書（本・雑誌）\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u30002週間以内\nCD・カセットテープ・ビデオテープ・DVD\u30001週間以内\n※貸し出し期間の算定は、貸し出し日の翌日からとなります。\n※貸し出し期間は、申し込みのあった日から2週間だけ延長することができます。\n\u3000電話でのお申し込みも受け付けます。\n\u3000（ただし、期限切れや予約が入っている図書の延長はできません。また、CDやビデオなどの視聴覚資料の延長はできませんのでご了承ください。）',
        "question": '【問題14】図書館カードを見せれば雑誌を借りることができるか。',
        "option_a": '合計8冊までなら借りることができる。',
        "option_b": '館内で読めるが借りることはできない。',
        "option_c": 'どれでも1人5冊までなら借りられる。',
        "option_d": '最新号以外は1人5冊まで借りられる。',
        "correct_answer": 'd',
        "explanation": '利用案内：「図書（本・雑誌）1人5冊まで」「ただし、雑誌の最新号は貸し出しできません」→ 最新號不能借，其他雜誌最多5冊。選項c未排除最新號，選項a（8冊）是圖書+CD合計上限。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「どんな状況でも冷静さを保つことが大切だ。」下線部「冷静」の読み方として最もよいものはどれですか。',
        "option_a": 'れいじょう',
        "option_b": 'れいせい',
        "option_c": 'ひやむ',
        "option_d": 'れいてい',
        "correct_answer": 'b',
        "explanation": '冷静（れいせい）＝ 冷靜、沉著。「冷」は「れい」、「静」は「せい」。「冷静を保つ」＝ 保持冷靜。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「この体験は、私にとって貴重な経験だった。」下線部「貴重」の読み方として最もよいものはどれですか。',
        "option_a": 'かちょう',
        "option_b": 'きじゅう',
        "option_c": 'きちょう',
        "option_d": 'かじゅう',
        "correct_answer": 'c',
        "explanation": '貴重（きちょう）＝ 珍貴、寶貴。「貴」は「き」、「重」は「ちょう」。形容詞として「貴重な」の形で使う。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「電車が定刻に到着した。」下線部「到着」の読み方として最もよいものはどれですか。',
        "option_a": 'とうちゃく',
        "option_b": 'とうちゅく',
        "option_c": 'どうちゃく',
        "option_d": 'とうしゃく',
        "correct_answer": 'a',
        "explanation": '到着（とうちゃく）＝ 到達、抵達。「到」は「とう」、「着」は「ちゃく」。対義語は「出発（しゅっぱつ）」。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「この図書館には豊富な資料が揃っている。」下線部「豊富」の読み方として最もよいものはどれですか。',
        "option_a": 'ほうぷ',
        "option_b": 'ほうふ',
        "option_c": 'ぼうふ',
        "option_d": 'とよふ',
        "correct_answer": 'b',
        "explanation": '豊富（ほうふ）＝ 豐富。「豊」は「ほう」（訓読みは「ゆた」）、「富」は「ふ」。「資料が豊富だ」＝ 資料齊全。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「患者の〈じょうたい〉が改善してきた。」下線部の言葉を漢字で書くとき最もよいものはどれですか。',
        "option_a": '条態',
        "option_b": '状体',
        "option_c": '状態',
        "option_d": '場体',
        "correct_answer": 'c',
        "explanation": '状態（じょうたい）＝ 狀態、情況。「状」は「じょう」、「態」は「たい」。「状況（じょうきょう）」と混同しないように。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「環境〈ほぜん〉のために、ごみの分別が義務づけられた。」下線部の言葉を漢字で書くとき最もよいものはどれですか。',
        "option_a": '保存',
        "option_b": '保善',
        "option_c": '保選',
        "option_d": '保全',
        "correct_answer": 'd',
        "explanation": '保全（ほぜん）＝ 保護、維護。「保存（ほぞん）」は保留物品，讀音和意思都不同。「環境保全」是固定搭配。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「チームは優勝を〈断念した〉。」下線部の言葉に意味が最も近いものはどれですか。',
        "option_a": '達成した',
        "option_b": '延期した',
        "option_c": 'あきらめた',
        "option_d": '決定した',
        "correct_answer": 'c',
        "explanation": '断念（だんねん）する＝ 放棄、死心。與「あきらめる」意思相近。「延期した」是延後，「達成した」是達成，均相反。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '「この問題は非常に〈厄介だ〉。」下線部の言葉に意味が最も近いものはどれですか。',
        "option_a": '大切だ',
        "option_b": 'めんどうだ',
        "option_c": '重要だ',
        "option_d": '深刻だ',
        "correct_answer": 'b',
        "explanation": '厄介（やっかい）＝ 麻煩、棘手。最近似「めんどうだ（麻煩）」。「重要だ」強調重要性，「深刻だ」強調嚴重性，語意不同。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '次の「素直」の言葉の使い方として最もよいものはどれですか。',
        "option_a": 'このケーキは素直においしい。',
        "option_b": '彼は素直に走り続けた。',
        "option_c": '彼女は素直に先生のアドバイスを受け入れた。',
        "option_d": '試験が素直に終わった。',
        "correct_answer": 'c',
        "explanation": '「素直（すなお）に受け入れる」＝ 坦率地、老實地接受。選項a應用「本当に」、b應用「まっすぐに」、d應用「無事に」。',
    },
    {
        "type": 'kanji',
        "context": None,
        "question": '次の「自慢」の言葉の使い方として最もよいものはどれですか。',
        "option_a": '彼は自慢の料理を友達に振る舞った。',
        "option_b": '彼女は自慢して失敗してしまった。',
        "option_c": '試験に自慢して合格した。',
        "option_d": 'この建物はとても自慢な設計だ。',
        "correct_answer": 'a',
        "explanation": '「自慢（じまん）の料理」＝ 引以為傲的料理。「自慢の＋名詞」是自然用法。選項b語意奇怪（因為自吹自擂所以失敗？），c應用「努力して」，d應用「すばらしい」。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「どんなに忙しくても、毎日日記を書く（\u3000）にしている。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'ところ',
        "option_b": 'こと',
        "option_c": 'もの',
        "option_d": 'はず',
        "correct_answer": 'b',
        "explanation": '「～することにしている」＝ 把某事定為習慣、規定自己要做。例：毎朝運動することにしている。「ものにしている」不自然，「はずにしている」文法錯誤。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「締め切りが明日なので、今日中に仕上げない（\u3000）。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'わけではない',
        "option_b": 'わけにはいかない',
        "option_c": 'はずがない',
        "option_d": 'ことになっている',
        "correct_answer": 'b',
        "explanation": '「～ないわけにはいかない」＝ 不得不、不能不做。（因明天是截止日，今天非得完成不可。）「わけではない」是否定原因，「はずがない」表不可能，均不符。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「健康（\u3000）、どんなことも乗り越えられる。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'だからこそ',
        "option_b": 'さえあれば',
        "option_c": 'であっても',
        "option_d": 'によって',
        "correct_answer": 'b',
        "explanation": '「健康さえあれば」＝ 只要有健康，（什麼都能克服）。「さえ～ば」表示「只要這個條件滿足就夠了」。「だからこそ」是「正因如此」，「であっても」是「即使」，語意不符。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「留学した（\u3000）、語学の勉強に真剣に取り組むようになった。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'ことに',
        "option_b": 'ために',
        "option_c": 'のに',
        "option_d": 'をきっかけに',
        "correct_answer": 'd',
        "explanation": '「～をきっかけに」＝ 以…為契機、以…為轉折點。例：病気をきっかけに、健康に気をつけるようになった。「ために」表目的，「ことに」語意不合。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「計画を立てた（\u3000）、実行に移せていない。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'ものの',
        "option_b": 'ので',
        "option_c": 'から',
        "option_d": 'ために',
        "correct_answer": 'a',
        "explanation": '「～ものの」＝ 雖然…但是…（逆接）。雖然擬了計劃，卻沒能付諸行動。「ので・から・ために」都是表原因，接下文應為相符的結果，不符合逆接語意。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「強風（\u3000）、運動会は予定通り開催された。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'のうえに',
        "option_b": 'にもかかわらず',
        "option_c": 'のために',
        "option_d": 'によって',
        "correct_answer": 'b',
        "explanation": '「～にもかかわらず」＝ 儘管…、雖然…（逆接）。即使颳著強風，運動會仍按計劃舉行。「のうえに」是「而且」（累加），「のために」是因果，語意相反。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「彼はずっと練習してきたのだから、失敗する（\u3000）。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'わけがない',
        "option_b": 'わけではない',
        "option_c": 'はずではない',
        "option_d": 'ことはない',
        "correct_answer": 'a',
        "explanation": '「失敗するわけがない」＝ 不可能失敗（說話者的強烈確信）。「わけではない」是部分否定（並非…），「ことはない」是不必要，語感不同。',
    },
    {
        "type": 'grammar',
        "context": None,
        "question": '「この映画は日本（\u3000）、世界中で人気がある。」（\u3000）に入れるのに最もよいものはどれですか。',
        "option_a": 'に限らず',
        "option_b": 'に対して',
        "option_c": 'において',
        "option_d": 'に関して',
        "correct_answer": 'a',
        "explanation": '「日本に限らず世界中で」＝ 不僅在日本，在全世界都…。「に限らず」＝ 不限於。「において」是「在…方面」，「に対して」是「對於…」，均語意不合。',
    },
    {
        "type": 'grammar',
        "context": '【問題8 ★排列】次の文の＿★＿に入る最もよいものを選んでください。\n\n文：「彼女が ___ ___ ★ ___ 、みんなが驚いた。」\n【語句】1 と\u30002 合格した\u30003 聞いて\u30004 試験に\n【正しい語順】試験に(4) → 合格した(2) → と(1) → 聞いて(3)',
        "question": '★の位置（3番目）に入る語句はどれですか。',
        "option_a": 'と',
        "option_b": '合格した',
        "option_c": '聞いて',
        "option_d": '試験に',
        "correct_answer": 'a',
        "explanation": '正しい語順：「彼女が 試験に 合格した と 聞いて、みんなが驚いた」。★は3番目なので「と」。「試験に合格したと聞いて」＝ 聽說她通過了考試（之後大家都驚訝了）。',
    },
    {
        "type": 'grammar',
        "context": '【問題8 ★排列】次の文の＿★＿に入る最もよいものを選んでください。\n\n文：「その映画は ___ ★ ___ ___ という評判だ。」\n【語句】1 泣ける\u30002 とても\u30003 感動して\u30004 ほど\n【正しい語順】とても(2) → 感動して(3) → 泣ける(1) → ほど(4)',
        "question": '★の位置（2番目）に入る語句はどれですか。',
        "option_a": '泣ける',
        "option_b": 'とても',
        "option_c": '感動して',
        "option_d": 'ほど',
        "correct_answer": 'c',
        "explanation": '正しい語順：「その映画は とても 感動して 泣ける ほど という評判だ」。★は2番目なので「感動して」。「感動して泣けるほど」＝ 感動到會哭的程度。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000近年、人工知能（AI）の発展が急速に進んでいる。医療、教育、交通など、様々な分野でAI技術の活用が広がりつつある。特に医療の分野では、AIが画像診断を補助することで、医師の見落としを減らす効果が期待されている。\n\u3000しかし、AI技術の普及に伴い、懸念される問題もある。まず、雇用への影響だ。これまで人間が行っていた作業をAIが代替するようになると、一部の職業が失われる可能性がある。また、プライバシーの問題もある。AIが大量のデータを収集・分析することで、個人情報が適切に管理されない恐れがある。\n\u3000AIを社会にうまく取り入れるためには、技術の進歩だけでなく、それを活用するための倫理的な枠組みや法整備も同時に進めていく必要がある。',
        "question": 'AIに関する問題として文章に述べられていないものはどれですか。',
        "option_a": '雇用への影響',
        "option_b": 'プライバシーの問題',
        "option_c": '教育格差の拡大',
        "option_d": '一部の職業が失われる可能性',
        "correct_answer": 'c',
        "explanation": '文章中に「雇用への影響」「プライバシーの問題」「職業が失われる可能性」は述べられているが、「教育格差の拡大」については触れていない。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000近年、人工知能（AI）の発展が急速に進んでいる。医療、教育、交通など、様々な分野でAI技術の活用が広がりつつある。特に医療の分野では、AIが画像診断を補助することで、医師の見落としを減らす効果が期待されている。\n\u3000しかし、AI技術の普及に伴い、懸念される問題もある。まず、雇用への影響だ。これまで人間が行っていた作業をAIが代替するようになると、一部の職業が失われる可能性がある。また、プライバシーの問題もある。AIが大量のデータを収集・分析することで、個人情報が適切に管理されない恐れがある。\n\u3000AIを社会にうまく取り入れるためには、技術の進歩だけでなく、それを活用するための倫理的な枠組みや法整備も同時に進めていく必要がある。',
        "question": '医療分野でのAI活用に期待されていることは何ですか。',
        "option_a": '手術を自動で行うこと',
        "option_b": '医師の見落としを減らすこと',
        "option_c": '病院の経営を改善すること',
        "option_d": '薬を自動で処方すること',
        "correct_answer": 'b',
        "explanation": '文章：「AIが画像診断を補助することで、医師の見落としを減らす効果が期待されている」。選項a・c・dは文中に記載なし。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000近年、人工知能（AI）の発展が急速に進んでいる。医療、教育、交通など、様々な分野でAI技術の活用が広がりつつある。特に医療の分野では、AIが画像診断を補助することで、医師の見落としを減らす効果が期待されている。\n\u3000しかし、AI技術の普及に伴い、懸念される問題もある。まず、雇用への影響だ。これまで人間が行っていた作業をAIが代替するようになると、一部の職業が失われる可能性がある。また、プライバシーの問題もある。AIが大量のデータを収集・分析することで、個人情報が適切に管理されない恐れがある。\n\u3000AIを社会にうまく取り入れるためには、技術の進歩だけでなく、それを活用するための倫理的な枠組みや法整備も同時に進めていく必要がある。',
        "question": 'この文章で筆者が最も言いたいことは何ですか。',
        "option_a": 'AIの技術的な進歩をできるだけ早く進めることが大切だ。',
        "option_b": 'AIの普及を止めて、人間の雇用と個人情報を守るべきだ。',
        "option_c": 'AI活用のためには、技術の進歩と倫理・法整備を同時に進める必要がある。',
        "option_d": '医療分野でのAI活用を最優先に進めるべきだ。',
        "correct_answer": 'c',
        "explanation": '最終段落：「技術の進歩だけでなく、倫理的な枠組みや法整備も同時に進めていく必要がある」が筆者の主張。選項b（止めるべき）は文意と正反対。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000現代人の多くが睡眠不足に悩んでいる。厚生労働省の調査によると、日本人の平均睡眠時間は先進国の中でも特に短く、慢性的な睡眠不足を抱える人が増えている。\n\u3000睡眠は単なる「休息」ではない。眠っている間、脳は記憶を整理し、免疫機能を回復させ、成長ホルモンを分泌するなど、多くの重要な働きをしている。睡眠が不足すると、集中力や判断力が低下するだけでなく、長期的には生活習慣病やうつ病のリスクが高まるとされている。\n\u3000良質な睡眠を得るためには、毎日同じ時間に寝起きすること、寝る前にスマートフォンを見ないこと、適度な運動をすることなどが効果的だとされている。睡眠の質を高めることは、健康管理の基本であると言えるだろう。',
        "question": '眠っている間に行われることとして文章に述べられていないものはどれですか。',
        "option_a": '記憶の整理',
        "option_b": '免疫機能の回復',
        "option_c": 'カロリーの消費',
        "option_d": '成長ホルモンの分泌',
        "correct_answer": 'c',
        "explanation": '文章中に記憶の整理・免疫機能の回復・成長ホルモンの分泌は明記されているが、「カロリーの消費」については触れていない。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000現代人の多くが睡眠不足に悩んでいる。厚生労働省の調査によると、日本人の平均睡眠時間は先進国の中でも特に短く、慢性的な睡眠不足を抱える人が増えている。\n\u3000睡眠は単なる「休息」ではない。眠っている間、脳は記憶を整理し、免疫機能を回復させ、成長ホルモンを分泌するなど、多くの重要な働きをしている。睡眠が不足すると、集中力や判断力が低下するだけでなく、長期的には生活習慣病やうつ病のリスクが高まるとされている。\n\u3000良質な睡眠を得るためには、毎日同じ時間に寝起きすること、寝る前にスマートフォンを見ないこと、適度な運動をすることなどが効果的だとされている。睡眠の質を高めることは、健康管理の基本であると言えるだろう。',
        "question": '睡眠不足の影響として述べられているものはどれですか。',
        "option_a": '食欲が増える',
        "option_b": '体重が増加する',
        "option_c": '集中力や判断力が低下する',
        "option_d": '記憶力が向上する',
        "correct_answer": 'c',
        "explanation": '文章：「睡眠が不足すると、集中力や判断力が低下するだけでなく、生活習慣病やうつ病のリスクが高まる」。選項a・b・dは文中に記載なし。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000現代人の多くが睡眠不足に悩んでいる。厚生労働省の調査によると、日本人の平均睡眠時間は先進国の中でも特に短く、慢性的な睡眠不足を抱える人が増えている。\n\u3000睡眠は単なる「休息」ではない。眠っている間、脳は記憶を整理し、免疫機能を回復させ、成長ホルモンを分泌するなど、多くの重要な働きをしている。睡眠が不足すると、集中力や判断力が低下するだけでなく、長期的には生活習慣病やうつ病のリスクが高まるとされている。\n\u3000良質な睡眠を得るためには、毎日同じ時間に寝起きすること、寝る前にスマートフォンを見ないこと、適度な運動をすることなどが効果的だとされている。睡眠の質を高めることは、健康管理の基本であると言えるだろう。',
        "question": '良質な睡眠のために効果的とされていることはどれですか。',
        "option_a": '寝る前にリラックスのためにスマートフォンを見る',
        "option_b": '毎日同じ時間に寝起きする',
        "option_c": 'できるだけ長い時間を確保して眠る',
        "option_d": '日中に激しい運動を行う',
        "correct_answer": 'b',
        "explanation": '文章：「毎日同じ時間に寝起きすること、寝る前にスマートフォンを見ないこと、適度な運動をすること」が効果的。選項a（寝る前にスマホを見る）は文章と反対の内容。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000ボランティア活動とは、自発的に社会や他者のために行う無償の活動のことである。日本では、1995年の阪神・淡路大震災を機に、ボランティア活動への関心が急速に高まり、「ボランティア元年」とも呼ばれるようになった。\n\u3000ボランティア活動には様々なメリットがある。参加者にとっては、新しいスキルを身につけたり、様々な人との出会いを通じて視野が広がったりするという利点がある。また、社会全体にとっても、地域のつながりが強化されるという効果がある。\n\u3000一方で、ボランティア活動が継続しない問題もある。活動に参加したいと思っても、時間の確保が難しかったり、どのような活動があるか情報が得にくかったりする人も多い。こうした課題を解決するために、企業がボランティア休暇制度を導入したり、情報をまとめるポータルサイトが整備されたりする取り組みが進められている。',
        "question": 'ボランティア活動のメリットとして述べられているものはどれですか。',
        "option_a": '収入が増える',
        "option_b": '視野が広がり、地域のつながりが強化される',
        "option_c": '専門的な資格が取れる',
        "option_d": '就職に有利になる',
        "correct_answer": 'b',
        "explanation": '文章：「視野が広がる」（個人のメリット）と「地域のつながりが強化される」（社会全体のメリット）の二点が述べられている。収入・資格・就職については記載なし。',
    },
    {
        "type": 'reading',
        "context": '【問題文】\n\u3000ボランティア活動とは、自発的に社会や他者のために行う無償の活動のことである。日本では、1995年の阪神・淡路大震災を機に、ボランティア活動への関心が急速に高まり、「ボランティア元年」とも呼ばれるようになった。\n\u3000ボランティア活動には様々なメリットがある。参加者にとっては、新しいスキルを身につけたり、様々な人との出会いを通じて視野が広がったりするという利点がある。また、社会全体にとっても、地域のつながりが強化されるという効果がある。\n\u3000一方で、ボランティア活動が継続しない問題もある。活動に参加したいと思っても、時間の確保が難しかったり、どのような活動があるか情報が得にくかったりする人も多い。こうした課題を解決するために、企業がボランティア休暇制度を導入したり、情報をまとめるポータルサイトが整備されたりする取り組みが進められている。',
        "question": 'ボランティア活動が継続しない理由として文章に述べられていないものはどれですか。',
        "option_a": '時間の確保が難しい',
        "option_b": 'どのような活動があるか情報が得にくい',
        "option_c": '活動場所が遠い',
        "option_d": '参加したい活動が分からない',
        "correct_answer": 'c',
        "explanation": '文章では「時間の確保が難しい」「情報が得にくい」が継続しない理由として挙げられている。「活動場所が遠い」については述べられていない。',
    },
    {
        "type": 'reading',
        "context": '【さくら日本語学校 夏期集中コースのご案内】\n\n★ 開催期間：7月21日（月）〜 8月22日（金）（土日祝除く）\n★ 対象：JLPT N3合格者または同等レベルの方\n★ クラス：N2準備コース・N2直前コース（各20名定員）\n★ 授業料：N2準備コース 45,000円 / N2直前コース 55,000円\n★ 申込締め切り：7月7日（月）17:00まで（定員になり次第締め切り）\n\n◎ N2準備コース：語彙・文法・読解を基礎から丁寧に学ぶ\n◎ N2直前コース：模擬試験と弱点補強に特化したカリキュラム\n\n【お申し込み方法】\n学校ウェブサイトのフォーム、または窓口（平日9:00〜17:00）にてお申し込みください。\n\n【ご注意】\n・申込後のキャンセルは7月14日まで受け付けます。以降のキャンセルは返金いたしません。\n・授業料は申込時に全額お支払いください。\n・欠席した授業の振り替えはできません。',
        "question": 'N2直前コースの授業料はいくらですか。',
        "option_a": '45,000円',
        "option_b": '55,000円',
        "option_c": '100,000円',
        "option_d": '20,000円',
        "correct_answer": 'b',
        "explanation": '案内文：「N2直前コース 55,000円」。N2準備コースは45,000円。どちらのコースかに注意。',
    },
    {
        "type": 'reading',
        "context": '【さくら日本語学校 夏期集中コースのご案内】\n\n★ 開催期間：7月21日（月）〜 8月22日（金）（土日祝除く）\n★ 対象：JLPT N3合格者または同等レベルの方\n★ クラス：N2準備コース・N2直前コース（各20名定員）\n★ 授業料：N2準備コース 45,000円 / N2直前コース 55,000円\n★ 申込締め切り：7月7日（月）17:00まで（定員になり次第締め切り）\n\n◎ N2準備コース：語彙・文法・読解を基礎から丁寧に学ぶ\n◎ N2直前コース：模擬試験と弱点補強に特化したカリキュラム\n\n【お申し込み方法】\n学校ウェブサイトのフォーム、または窓口（平日9:00〜17:00）にてお申し込みください。\n\n【ご注意】\n・申込後のキャンセルは7月14日まで受け付けます。以降のキャンセルは返金いたしません。\n・授業料は申込時に全額お支払いください。\n・欠席した授業の振り替えはできません。',
        "question": 'この案内の内容と合っているものはどれですか。',
        "option_a": '土曜日も授業が行われる。',
        "option_b": '7月7日を過ぎても申し込める場合がある。',
        "option_c": '申込後のキャンセルは7月14日まで受け付ける。',
        "option_d": '欠席した場合は振り替え授業が受けられる。',
        "correct_answer": 'c',
        "explanation": '案内文：「申込後のキャンセルは7月14日まで受け付けます」→ 選項c正確。選項a（土日は除く）・d（振り替え不可）は案内と反対。選項b（定員になり次第締め切り）の記載から7日後に申し込める保証はない。',
    },
]
